"""The /demo page and its proxies, with the MusicGen service faked."""
from __future__ import annotations

import json

from fastapi.testclient import TestClient

import services.musicgen_client as mg
import services.notation_service as svc
from main import app

client = TestClient(app)


def test_page_is_served_plain():
    r = client.get("/demo")
    assert r.status_code == 200 and "text/html" in r.headers["content-type"]
    assert "Transcribe a recording" in r.text and "Generate with the fine-tuned model" in r.text
    assert "<script src=" not in r.text  # no framework, no build step


def test_config_reports_the_generation_service(monkeypatch):
    monkeypatch.setattr(mg, "status", lambda: {"available": True, "adapters": ["base", "oud"], "base_model": "m", "device": "mps", "url": "u"})
    assert client.get("/demo/config").json()["generation"]["adapters"] == ["base", "oud"]
    monkeypatch.setattr(mg, "status", lambda: {"available": False, "adapters": [], "detail": "down", "url": "u"})
    assert client.get("/demo/config").json()["generation"]["available"] is False


def test_generate_and_audio_are_proxied(monkeypatch):
    seen = {}

    def fake_generate(prompt, adapter, duration, seed):
        seen.update(prompt=prompt, adapter=adapter, duration=duration, seed=seed)
        return {"id": "abcdef0123456789", "adapter": adapter, "duration": duration, "total_seconds": 3.2,
                "provenance": "generated by a test", "pcs": {"pcs": 0.9, "voiced_fraction": 0.5}}

    monkeypatch.setattr(mg, "generate", fake_generate)
    monkeypatch.setattr(mg, "audio", lambda gen_id: b"RIFF" + gen_id.encode())
    r = client.post("/demo/generate", json={"prompt": "Somali qaraami on the oud", "adapter": "oud", "duration": 8, "seed": 7})
    assert r.status_code == 200 and r.json()["audio"] == "/demo/audio/abcdef0123456789"
    assert seen == {"prompt": "Somali qaraami on the oud", "adapter": "oud", "duration": 8, "seed": 7}
    a = client.get("/demo/audio/abcdef0123456789")
    assert a.status_code == 200 and a.headers["content-type"].startswith("audio/wav") and a.content.startswith(b"RIFF")
    assert client.get("/demo/audio/not-hex!").status_code == 404
    assert client.post("/demo/generate", json={"prompt": "x"}).status_code == 422


def test_generate_reports_a_down_service_as_502(monkeypatch):
    def boom(*a, **k):
        raise RuntimeError("connection refused")

    monkeypatch.setattr(mg, "generate", boom)
    r = client.post("/demo/generate", json={"prompt": "Somali qaraami on the oud"})
    assert r.status_code == 502 and "connection refused" in r.json()["detail"]


def test_stem_artifacts_are_served_for_separated_jobs(tmp_path, monkeypatch):
    monkeypatch.setattr(svc, "JOBS_ROOT", tmp_path)
    job = tmp_path / "j1"
    stems = job / "stems" / "htdemucs" / "input.input"
    stems.mkdir(parents=True)
    (stems / "vocals.wav").write_bytes(b"RIFFvox")
    (job / "input.wav").write_bytes(b"RIFF")
    (job / "job.json").write_text(json.dumps({"job_id": "j1", "status": "done", "input": "input.wav",
                                              "artifact_stem": "input", "result": {}}))
    r = client.get("/notation/jobs/j1/artifacts/stem_vocals")
    assert r.status_code == 200 and r.content == b"RIFFvox" and r.headers["content-type"].startswith("audio/wav")
    assert client.get("/notation/jobs/j1/artifacts/stem_other").status_code == 404
