/**
 * Cloudflare R2 storage (S3-compatible) — presigned URL generation.
 *
 * CONVENTIONS.md hard rules enforced here:
 *   • audio NEVER flows through Node — clients PUT directly to R2 with a short-lived
 *     presigned upload URL (§8),
 *   • objects are keyed by a random UUID, NEVER the original filename (§11 Threat 5),
 *   • download URLs are signed and expire in 1 hour (§11 Threat 1).
 *
 * The bucket is private; the only way in or out is through these signed URLs.
 */

import { randomUUID } from 'node:crypto';
import {
  S3Client,
  PutObjectCommand,
  GetObjectCommand,
  HeadObjectCommand,
} from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { env } from '@/config/env';

/** Presigned upload URLs live for 15 minutes (ARCHITECTURE.md §8). */
const UPLOAD_URL_TTL_SECONDS = 15 * 60;
/** Presigned download URLs live for 1 hour (ARCHITECTURE.md §11 Threat 1). */
const DOWNLOAD_URL_TTL_SECONDS = 60 * 60;

const CONTENT_TYPE_EXTENSION: Record<string, string> = {
  'audio/wav': 'wav',
  'audio/webm': 'webm',
  'audio/flac': 'flac',
  'audio/mpeg': 'mp3',
  'application/pdf': 'pdf',
  'image/jpeg': 'jpg',
  'image/png': 'png',
};

/** Object-key namespaces — recordings (audio), library (scanned books), and
 * generated (AI-provider output; see uploadObject for why it exists). */
export type StoragePrefix = 'recordings' | 'library' | 'generated';

const client = new S3Client({
  region: 'auto',
  endpoint: `https://${env.R2_ACCOUNT_ID}.r2.cloudflarestorage.com`,
  credentials: {
    accessKeyId: env.R2_ACCESS_KEY_ID,
    secretAccessKey: env.R2_SECRET_ACCESS_KEY,
  },
});

export interface PresignedUpload {
  /** The URL the client PUTs the raw audio bytes to. */
  uploadUrl: string;
  /** The opaque object key stored on the recording — never the original filename. */
  fileKey: string;
  /** When the upload URL stops working (ISO-8601). */
  expiresAt: string;
}

/** Build a UUID object key with the correct extension for the content type. */
function buildFileKey(contentType: string, prefix: StoragePrefix): string {
  const ext = CONTENT_TYPE_EXTENSION[contentType] ?? 'bin';
  // Shard by first two hex chars to avoid a single giant flat prefix at scale.
  const id = randomUUID();
  return `${prefix}/${id.slice(0, 2)}/${id}.${ext}`;
}

export async function generateUploadUrl(
  contentType: string,
  prefix: StoragePrefix = 'recordings',
): Promise<PresignedUpload> {
  const fileKey = buildFileKey(contentType, prefix);
  const command = new PutObjectCommand({
    Bucket: env.R2_BUCKET_NAME,
    Key: fileKey,
    ContentType: contentType,
  });
  const uploadUrl = await getSignedUrl(client, command, { expiresIn: UPLOAD_URL_TTL_SECONDS });
  const expiresAt = new Date(Date.now() + UPLOAD_URL_TTL_SECONDS * 1000).toISOString();
  return { uploadUrl, fileKey, expiresAt };
}

export async function generateDownloadUrl(
  fileKey: string,
): Promise<{ url: string; expiresAt: string }> {
  const command = new GetObjectCommand({ Bucket: env.R2_BUCKET_NAME, Key: fileKey });
  const url = await getSignedUrl(client, command, { expiresIn: DOWNLOAD_URL_TTL_SECONDS });
  const expiresAt = new Date(Date.now() + DOWNLOAD_URL_TTL_SECONDS * 1000).toISOString();
  return { url, expiresAt };
}

/**
 * Server-side PutObject — the ONE deliberate, user-approved exception to the
 * "audio never uploads through Node" hard rule, scoped strictly to
 * PROVIDER-GENERATED audio (modules/generation). Rationale: Lyria returns the
 * generated bytes base64-inline in the API's own HTTP response, so they are
 * already in Node by construction; carrying them onward as data: URIs breaks
 * production (Upstash Redis 1MB value cap, ~4.5MB Vercel response cap). The
 * rule's actual target — user-upload request bodies — is untouched: clients
 * still PUT directly to R2 via presigned URLs, keys are UUIDs, the bucket
 * stays private behind signed 1-hour download URLs.
 */
export async function uploadObject(
  bytes: Uint8Array,
  contentType: string,
  prefix: StoragePrefix,
): Promise<{ fileKey: string }> {
  const fileKey = buildFileKey(contentType, prefix);
  await client.send(
    new PutObjectCommand({
      Bucket: env.R2_BUCKET_NAME,
      Key: fileKey,
      Body: bytes,
      ContentType: contentType,
    }),
  );
  return { fileKey };
}

/** Verify an uploaded object actually exists in R2 (called on upload-complete, §8). */
export async function objectExists(fileKey: string): Promise<boolean> {
  try {
    await client.send(new HeadObjectCommand({ Bucket: env.R2_BUCKET_NAME, Key: fileKey }));
    return true;
  } catch {
    return false;
  }
}

/** Alias — a signed GET URL for playback (1-hour expiry). Named per §8/SESSION P1-04. */
export const generatePlaybackUrl = generateDownloadUrl;
/** Alias — confirm the object exists before processing. */
export const verifyExists = objectExists;

/**
 * "Delete" a recording's audio — a SOFT delete by design (CONVENTIONS.md hard rule,
 * Principle 4: recordings are NEVER destroyed). The bytes stay in R2; removal from
 * the archive is a database/visibility change, not an object deletion. This exists
 * as the single, explicit place that decision is enforced — it deliberately does
 * NOT issue a DeleteObjectCommand.
 */
export async function deleteFile(fileKey: string): Promise<void> {
  void fileKey; // intentionally a no-op against R2; soft delete happens in the DB.
}
