"""Serve the A/B listening sets on loopback so they can be heard side by side,
and run a blind paired comparison on any of them.

The listening test is the arbiter for every adapter in the programme, and the
sets already exist on disk: the same seeded captions generated by a base model
and by its adapter. The index page puts them next to each other with the scores
that were computed when they were generated. The test page (/test/<set>) hides
the scores and the file names, presents each pair as A and B in an order drawn
at random per pair, records which one the listener prefers, and writes the
result to data/listening/<set>_<listener>_<timestamp>.json with a Wilson 95%
interval on the adapter preference rate. build_demo_page.py reads those files.

Sets picked up when present:
  data/ab_<tag>/               pairNNN_{base,adapter}.wav + runs/qaraami_<tag>_r32/eval_<tag>.json
  data/oud_ab_listening/       pairNNN_{base,finetuned}.wav + data/eval_pcs/oud_{base,lora500}.csv
  data/harvard_ab_listening/   pairNNN_{base,finetuned}.wav + data/eval_pcs/harvard_{base,lora1500}.csv
  data/ab_melody/              melodyNNN_base.wav + melody_condition.json

Binds 127.0.0.1 only. Serves nothing but these generated clips; source audio is
never on this page. Stdlib only.

Usage (from the repo root):
  python apps/ai-service/scripts/ab_listen.py            # http://127.0.0.1:8777
  python apps/ai-service/scripts/ab_listen.py --open     # and open it in the browser
"""
from __future__ import annotations

import argparse
import csv
import datetime as dt
import html
import json
import math
import os
import random
import re
import secrets
import sys
import webbrowser
from dataclasses import dataclass, field
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlparse

REPO = Path(__file__).resolve().parents[3]
DATA = REPO / "data"
RUNS = REPO / "runs"
LISTENING = Path(os.environ.get("QG_LISTENING_DIR", DATA / "listening"))
WAV_NAME = re.compile(r"^[A-Za-z0-9_]+\.wav$")
PAIR = re.compile(r"pair(\d{3})_(base|adapter|finetuned)\.wav$")


@dataclass
class Clip:
    file: str
    pcs: float | None = None
    voiced: float | None = None
    tonic: str | None = None
    tuning: float | None = None


@dataclass
class Pair:
    index: int
    caption: str
    base: Clip | None = None
    adapter: Clip | None = None


@dataclass
class ListeningSet:
    name: str          # URL segment and directory name under data/
    title: str
    dir: Path
    note: str = ""
    pairs: list[Pair] = field(default_factory=list)
    summary: dict = field(default_factory=dict)

    @property
    def testable(self) -> bool:
        return any(p.base and p.adapter for p in self.pairs)


def read_captions(d: Path) -> dict[int, str]:
    out: dict[int, str] = {}
    p = d / "CAPTIONS.txt"
    if not p.exists():
        return out
    for line in p.read_text().splitlines():
        m = re.match(r"pair(\d{3}):\s*(.*)", line)
        if m:
            out[int(m.group(1))] = m.group(2).strip()
    return out


def scan_pairs(d: Path) -> dict[int, Pair]:
    captions = read_captions(d)
    pairs: dict[int, Pair] = {}
    for f in sorted(d.glob("pair*.wav")):
        m = PAIR.search(f.name)
        if not m:
            continue
        i = int(m.group(1))
        pair = pairs.setdefault(i, Pair(i, captions.get(i, "")))
        clip = Clip(f.name)
        if m.group(2) == "base":
            pair.base = clip
        else:
            pair.adapter = clip
    return pairs


def scale_set(tag: str) -> ListeningSet | None:
    d = DATA / f"ab_{tag}"
    ev = RUNS / f"qaraami_{tag}_r32" / f"eval_{tag}.json"
    if not d.is_dir():
        return None
    s = ListeningSet(f"ab_{tag}", f"MusicGen-{tag}", d)
    pairs = scan_pairs(d)
    if ev.exists():
        e = json.loads(ev.read_text())
        ce = e["per_song_ce"]
        imp = ce["improvement_base_minus_adapter"]
        s.summary = {
            "model": e["model"],
            "best_ckpt": e["best_ckpt"],
            "songs": ce["n_songs"],
            "ce_base": ce["base"]["mean"],
            "ce_adapter": ce["adapter"]["mean"],
            "ce_gain": imp["mean"],
            "ce_ci": imp["ci95"],
            "significant": imp["significant"],
            "pcs_base": e["ab"]["base"]["pcs_mean"],
            "pcs_adapter": e["ab"]["adapter"]["pcs_mean"],
            "voiced_base": e["ab"]["base"]["voiced_fraction_mean"],
            "voiced_adapter": e["ab"]["adapter"]["voiced_fraction_mean"],
        }
        for row in e["ab"]["pairs"]:
            pair = pairs.get(row["pair"])
            if pair is None:
                continue
            if not pair.caption:
                pair.caption = row.get("caption", "")
            for side in ("base", "adapter"):
                clip = getattr(pair, side)
                sc = row.get(side) or {}
                if clip and sc.get("scored"):
                    clip.pcs = sc.get("pcs")
                    clip.voiced = sc.get("voiced_fraction")
                    clip.tonic = sc.get("tonic")
                    clip.tuning = sc.get("tuning_offset_cents")
        s.note = f"{e['model']}, best checkpoint {e['best_ckpt']}; same 16 captions and seeds as every other scale set."
    s.pairs = [pairs[i] for i in sorted(pairs)]
    return s


def pcs_csv(name: str) -> dict[int, dict]:
    """Per-clip scores from data/eval_pcs/<name>.csv keyed by pair index.

    The scorer names clips gen_NNN in the order they were generated, which is
    the pair order of the listening set; pairNNN is accepted too.
    """
    p = DATA / "eval_pcs" / f"{name}.csv"
    out: dict[int, dict] = {}
    if not p.exists():
        return out
    with p.open() as fh:
        for row in csv.DictReader(fh):
            m = re.search(r"(?:pair|gen_)(\d{3})", str(row.get("clip", "")))
            if m:
                out[int(m.group(1))] = row
    return out


def _num(row: dict, *keys: str) -> float | None:
    for k in keys:
        if k in row and row[k] not in ("", None):
            try:
                return float(row[k])
            except ValueError:
                pass
    return None


def legacy_set(name: str, title: str, base_group: str, ft_group: str, note: str) -> ListeningSet | None:
    d = DATA / name
    if not d.is_dir():
        return None
    s = ListeningSet(name, title, d, note)
    pairs = scan_pairs(d)
    for side, group in (("base", base_group), ("adapter", ft_group)):
        rows = pcs_csv(group)
        for i, row in rows.items():
            clip = getattr(pairs.get(i), side, None) if i in pairs else None
            if clip:
                clip.pcs = _num(row, "pcs", "pcs_score")
                clip.voiced = _num(row, "voiced_fraction", "voiced")
                clip.tonic = row.get("tonic") or None
                clip.tuning = _num(row, "tuning_offset_cents", "tuning_offset")
    for group, key in ((base_group, "base"), (ft_group, "adapter")):
        j = DATA / "eval_pcs" / f"{group}.json"
        if j.exists():
            g = json.loads(j.read_text())
            s.summary[f"pcs_{key}"] = g.get("pcs_mean")
            s.summary[f"voiced_{key}"] = g.get("voiced_fraction_mean")
    s.pairs = [pairs[i] for i in sorted(pairs)]
    return s


def melody_set() -> ListeningSet | None:
    d = DATA / "ab_melody"
    j = d / "melody_condition.json"
    if not d.is_dir():
        return None
    s = ListeningSet("ab_melody", "musicgen-melody, conditioned on real qaraami melodies", d)
    if j.exists():
        e = json.loads(j.read_text())
        s.note = (f"{e['model']}, no adapter, one caption: \"{e['caption']}\". "
                  f"Each clip follows the chroma of a held-out qaraami clip (named per row). "
                  f"Mean PCS {e['pcs_mean']:.3f}, voiced fraction {e['voiced_fraction_mean']:.3f}.")
        for c in e.get("clips", []):
            s.pairs.append(Pair(c["i"], f"melody from {c['ref']}",
                                base=Clip(c["file"], c.get("pcs"), c.get("voiced_fraction"))))
    else:
        for i, f in enumerate(sorted(d.glob("melody*_base.wav"))):
            s.pairs.append(Pair(i, "", base=Clip(f.name)))
    return s


def scored_set(d: Path) -> ListeningSet | None:
    """Any other data/ab_<name>/ with pairNNN_{base,adapter}.wav and an optional
    ab_scores.json (written by dpo_train.py: note + per-pair base/adapter terms)."""
    pairs = scan_pairs(d)
    if not pairs:
        return None
    s = ListeningSet(d.name, d.name.replace("_", " "), d)
    j = d / "ab_scores.json"
    if j.exists():
        e = json.loads(j.read_text())
        s.note = e.get("note", "")
        for row in e.get("pairs", []):
            pair = pairs.get(row["pair"])
            if pair is None:
                continue
            if not pair.caption:
                pair.caption = row.get("caption", "")
            for side in ("base", "adapter"):
                clip, sc = getattr(pair, side), row.get(side) or {}
                if clip and sc.get("pcs") is not None:
                    clip.pcs, clip.voiced = sc.get("pcs"), sc.get("voiced_fraction")
    readme = d / "README.txt"
    if readme.exists():
        s.note = (s.note + " " + readme.read_text().strip()).strip()
    s.pairs = [pairs[i] for i in sorted(pairs)]
    return s


def load_sets() -> list[ListeningSet]:
    sets: list[ListeningSet] = []
    for tag in ("medium", "large"):
        s = scale_set(tag)
        if s:
            sets.append(s)
    known = {"ab_medium", "ab_large", "ab_melody"}
    for d in sorted(DATA.glob("ab_*")):
        if d.is_dir() and d.name not in known:
            s = scored_set(d)
            if s:
                sets.append(s)
    s = legacy_set("oud_ab_listening", "MusicGen-small, oud adapter (step 500)", "oud_base", "oud_lora500",
                   "8 seeded oud captions, base vs the oud adapter; 10 s clips.")
    if s:
        sets.append(s)
    s = legacy_set("harvard_ab_listening", "MusicGen-small, harvard_raw adapter (step 1500)", "harvard_base",
                   "harvard_lora1500", "8 seeded Harvard test captions, base vs the harvard_raw adapter; 10 s clips.")
    if s:
        sets.append(s)
    s = melody_set()
    if s:
        sets.append(s)
    return sets


# ---------------------------------------------------------------- rendering

CSS = """
:root{--bg:#0C0B14;--panel:#15131f;--line:#2a2738;--ink:#ece7dc;--dim:#9a94a8;--accent:#C89B5F}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.45 Nunito,-apple-system,Helvetica,Arial,sans-serif}
main{max-width:1500px;margin:0 auto;padding:28px 24px 80px}
h1{font:600 28px/1.2 "Playfair Display",Georgia,serif;margin:0 0 6px}
h1 span{color:var(--accent)}
h2{font:600 20px/1.2 "Playfair Display",Georgia,serif;margin:36px 0 6px}
p.note{color:var(--dim);margin:0 0 14px}
a{color:var(--accent)}
table{border-collapse:collapse;width:100%;background:var(--panel);border:1px solid var(--line)}
th,td{border-top:1px solid var(--line);padding:8px 10px;text-align:left;vertical-align:top}
th{color:var(--dim);font-weight:600;font-size:13px}
td.n{color:var(--dim);white-space:nowrap}
td.cap{max-width:380px;color:var(--ink)}
td.clip{min-width:230px}
audio{width:100%;height:32px;display:block}
.score{color:var(--dim);font-size:12.5px;margin-top:4px;white-space:nowrap}
.score b{color:var(--ink);font-weight:600}
.up{color:#8fd19e}.down{color:#e39a8b}
.summary td,.summary th{white-space:nowrap}
.rights{margin-top:40px;color:var(--dim);font-size:13px;border-top:1px solid var(--line);padding-top:12px}
.testlink{font-size:13px;margin-left:12px;font-weight:400}
label.ch{display:inline-block;margin:6px 14px 0 0;cursor:pointer}
input[type=text]{background:var(--panel);color:var(--ink);border:1px solid var(--line);border-radius:4px;padding:8px 10px;font:inherit}
button{background:var(--accent);color:#1a1408;border:0;border-radius:4px;padding:10px 18px;font:600 15px Nunito,sans-serif;cursor:pointer}
.result{background:var(--panel);border:1px solid var(--line);padding:14px 16px;margin:14px 0}
"""

JS = """
document.addEventListener('play', e => {
  for (const a of document.querySelectorAll('audio')) if (a !== e.target) a.pause();
}, true);
"""


def esc(s: object) -> str:
    return html.escape(str(s))


def fmt(x: float | None, nd: int = 3) -> str:
    return "–" if x is None else f"{x:.{nd}f}"


def clip_cell(setname: str, clip: Clip | None) -> str:
    if clip is None:
        return '<td class="clip">–</td>'
    score = ""
    if clip.pcs is not None or clip.voiced is not None:
        parts = [f"PCS <b>{fmt(clip.pcs)}</b>", f"voiced <b>{fmt(clip.voiced)}</b>"]
        if clip.tonic:
            parts.append(f"tonic {esc(clip.tonic)}")
        if clip.tuning is not None:
            parts.append(f"{clip.tuning:+.0f} c")
        score = f'<div class="score">{" · ".join(parts)}</div>'
    src = f"/audio/{setname}/{clip.file}"
    return f'<td class="clip"><audio controls preload="none" src="{esc(src)}"></audio>{score}</td>'


def delta(a: float | None, b: float | None, nd: int = 3) -> str:
    if a is None or b is None:
        return "–"
    d = b - a
    cls = "up" if d > 0 else "down" if d < 0 else ""
    return f'<span class="{cls}">{d:+.{nd}f}</span>'


def test_link(s: ListeningSet) -> str:
    return f'<a class="testlink" href="/test/{esc(s.name)}">blind test →</a>' if s.testable else ""


def render_scale_summary(sets: list[ListeningSet]) -> str:
    rows = [s for s in sets if s.summary.get("ce_gain") is not None]
    if not rows:
        return ""
    out = ['<h2>Scale runs, held-out numbers</h2>',
           '<p class="note">Per-song test cross-entropy on unseen songs with a bootstrap 95% CI over songs; '
           'PCS and voiced fraction are means over the 16-clip A/B set below. Lower CE is better; '
           'voiced fraction is the share of frames with a trackable pitch.</p>',
           '<table class="summary"><tr><th>model</th><th>best ckpt</th><th>songs</th>'
           '<th>CE base → adapter</th><th>gain (nats), 95% CI</th>'
           '<th>PCS base → adapter</th><th>voiced base → adapter</th><th></th></tr>']
    for s in rows:
        m = s.summary
        sig = "significant" if m["significant"] else "not significant"
        out.append(
            f'<tr><td>{esc(m["model"])}</td><td>{esc(m["best_ckpt"])}</td><td>{m["songs"]}</td>'
            f'<td>{m["ce_base"]:.4f} → <b>{m["ce_adapter"]:.4f}</b></td>'
            f'<td>+{m["ce_gain"]:.3f} [{m["ce_ci"][0]:.3f}, {m["ce_ci"][1]:.3f}], {sig}</td>'
            f'<td>{m["pcs_base"]:.3f} → {m["pcs_adapter"]:.3f} ({delta(m["pcs_base"], m["pcs_adapter"])})</td>'
            f'<td>{m["voiced_base"]:.3f} → {m["voiced_adapter"]:.3f} ({delta(m["voiced_base"], m["voiced_adapter"])})</td>'
            f'<td>{test_link(s)}</td></tr>')
    out.append('</table>')
    return "\n".join(out)


def render_side_by_side(sets: list[ListeningSet]) -> str:
    """Scale sets share captions and seeds, so one row per caption with every model across."""
    scale = [s for s in sets if s.name.startswith("ab_") and s.name != "ab_melody"]
    if not scale:
        return ""
    n = max(len(s.pairs) for s in scale)
    out = ['<h2>Same prompt, same seed, every size</h2>',
           '<p class="note">Left to right within each model: base, then adapter. '
           'Playing a clip pauses the others.</p>',
           '<table><tr><th>#</th><th>caption</th>']
    for s in scale:
        out.append(f'<th>{esc(s.title)} · base</th><th>{esc(s.title)} · adapter</th>')
    out.append('</tr>')
    for i in range(n):
        caption = next((s.pairs[i].caption for s in scale if i < len(s.pairs) and s.pairs[i].caption), "")
        out.append(f'<tr><td class="n">{i:03d}</td><td class="cap">{esc(caption)}</td>')
        for s in scale:
            pair = s.pairs[i] if i < len(s.pairs) else None
            out.append(clip_cell(s.name, pair.base if pair else None))
            out.append(clip_cell(s.name, pair.adapter if pair else None))
        out.append('</tr>')
    out.append('</table>')
    return "\n".join(out)


def render_set(s: ListeningSet) -> str:
    out = [f'<h2>{esc(s.title)}{test_link(s)}</h2>']
    if s.note:
        out.append(f'<p class="note">{esc(s.note)}</p>')
    sm = s.summary
    if sm.get("pcs_base") is not None and sm.get("pcs_adapter") is not None:
        out.append(f'<p class="note">Set means: PCS {fmt(sm["pcs_base"])} → {fmt(sm["pcs_adapter"])} '
                   f'({delta(sm["pcs_base"], sm["pcs_adapter"])}), voiced fraction '
                   f'{fmt(sm.get("voiced_base"))} → {fmt(sm.get("voiced_adapter"))} '
                   f'({delta(sm.get("voiced_base"), sm.get("voiced_adapter"))}).</p>')
    two_sided = any(p.adapter for p in s.pairs)
    out.append('<table><tr><th>#</th><th>caption</th><th>base</th>' + ('<th>adapter</th>' if two_sided else '') + '</tr>')
    for p in s.pairs:
        out.append(f'<tr><td class="n">{p.index:03d}</td><td class="cap">{esc(p.caption)}</td>')
        out.append(clip_cell(s.name, p.base))
        if two_sided:
            out.append(clip_cell(s.name, p.adapter))
        out.append('</tr>')
    out.append('</table>')
    return "\n".join(out)


def page(title: str, body: str, sub: str = "") -> str:
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{esc(title)}</title><style>{CSS}</style></head><body><main>
<h1>Qaraami<span>Gen</span> — {esc(title)}</h1>
{f'<p class="note">{sub}</p>' if sub else ''}
{body}
<div class="rights">Every clip on this page is model output. The adapters were trained on recordings
that are not distributed and are not served here.</div>
</main><script>{JS}</script></body></html>"""


def render(sets: list[ListeningSet]) -> str:
    body = [render_scale_summary(sets), render_side_by_side(sets)]
    for s in sets:
        if s.name in ("ab_medium", "ab_large"):
            continue
        body.append(render_set(s))
    n_clips = sum((1 if p.base else 0) + (1 if p.adapter else 0) for s in sets for p in s.pairs)
    sub = (f"{len(sets)} sets, {n_clips} clips, all generated by the models named on each section. "
           f"Served from this machine only (127.0.0.1). Each two-sided set has a <b>blind test</b> link: "
           f"pairs as A/B in random order, no scores, result saved to data/listening/.")
    return page("listening sets", "".join(body), sub)


# --------------------------------------------------------------- blind test

SESSIONS: dict[str, dict] = {}


def wilson(k: int, n: int, z: float = 1.96) -> tuple[float, float]:
    if n == 0:
        return (0.0, 0.0)
    p = k / n
    d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return (c - h, c + h)


def new_session(s: ListeningSet) -> str:
    sid = secrets.token_urlsafe(12)
    seed = secrets.randbits(32)
    rng = random.Random(seed)
    order = {p.index: rng.random() < 0.5 for p in s.pairs if p.base and p.adapter}  # True: adapter is A
    SESSIONS[sid] = {"set": s.name, "seed": seed, "order": order, "created": dt.datetime.now().isoformat(timespec="seconds")}
    return sid


def render_test(s: ListeningSet, sid: str) -> str:
    sess = SESSIONS[sid]
    rows = []
    for p in s.pairs:
        if p.index not in sess["order"]:
            continue
        rows.append(
            f'<tr><td class="n">{p.index:03d}</td><td class="cap">{esc(p.caption)}</td>'
            f'<td class="clip"><audio controls preload="none" src="/blind/{sid}/{p.index}/A.wav"></audio></td>'
            f'<td class="clip"><audio controls preload="none" src="/blind/{sid}/{p.index}/B.wav"></audio></td>'
            f'<td><label class="ch"><input type="radio" name="c{p.index}" value="A"> A</label>'
            f'<label class="ch"><input type="radio" name="c{p.index}" value="B"> B</label>'
            f'<label class="ch"><input type="radio" name="c{p.index}" value="none"> neither</label>'
            f'<div><input type="text" name="n{p.index}" placeholder="note (optional)" style="width:100%;margin-top:6px"></div></td></tr>')
    body = f"""
<form id="f">
<p class="note">For every pair, listen to A and B in full, then choose the one that sounds more like
Somali qaraami to you, or <i>neither</i>. A/B order is random per pair; which is base and which is the
adapter is revealed only after you submit. Every pair needs an answer.</p>
<p>Listener: <input type="text" name="listener" value="khalid" required></p>
<table><tr><th>#</th><th>caption</th><th>A</th><th>B</th><th>which sounds more like qaraami?</th></tr>
{"".join(rows)}
</table>
<p style="margin-top:16px"><button type="submit">Submit</button> <span id="msg" class="note"></span></p>
</form>
<div id="out"></div>
<script>
document.getElementById('f').addEventListener('submit', async e => {{
  e.preventDefault();
  const fd = new FormData(e.target); const choices = {{}}, notes = {{}}; let missing = [];
  for (const [k, v] of fd.entries()) {{
    if (k.startsWith('c')) choices[k.slice(1)] = v; else if (k.startsWith('n') && v) notes[k.slice(1)] = v;
  }}
  for (const tr of document.querySelectorAll('tr')) {{
    const r = tr.querySelector('input[type=radio]'); if (r && !choices[r.name.slice(1)]) missing.push(tr.firstElementChild.textContent);
  }}
  if (missing.length) {{ document.getElementById('msg').textContent = 'missing: ' + missing.join(', '); return; }}
  const res = await fetch('/submit/{sid}', {{method: 'POST', headers: {{'content-type': 'application/json'}},
    body: JSON.stringify({{listener: fd.get('listener'), choices, notes}})}});
  document.getElementById('out').innerHTML = await res.text();
  document.getElementById('f').style.display = 'none';
  window.scrollTo(0, 0);
}});
</script>"""
    return page(f"blind test · {s.title}", body, esc(s.note))


def save_result(s: ListeningSet, sid: str, payload: dict) -> tuple[dict, Path]:
    sess = SESSIONS[sid]
    listener = re.sub(r"[^A-Za-z0-9_-]+", "_", str(payload.get("listener") or "listener")).strip("_") or "listener"
    choices = payload.get("choices") or {}
    notes = payload.get("notes") or {}
    pairs_out, counts = [], {"adapter": 0, "base": 0, "none": 0}
    for p in s.pairs:
        if p.index not in sess["order"]:
            continue
        adapter_is_a = sess["order"][p.index]
        c = choices.get(str(p.index))
        if c in ("A", "B"):
            choice = "adapter" if (c == "A") == adapter_is_a else "base"
        else:
            choice = "none"
        counts[choice] += 1
        pairs_out.append({"pair": p.index, "caption": p.caption, "A": "adapter" if adapter_is_a else "base",
                          "chosen": c or "none", "preferred": choice, "note": str(notes.get(str(p.index), ""))[:500]})
    n = sum(counts.values())
    lo, hi = wilson(counts["adapter"], n)
    result = {
        "set": s.name, "title": s.title, "listener": listener,
        "date": dt.datetime.now().isoformat(timespec="seconds"), "seed": sess["seed"],
        "protocol": "paired comparison, A/B order randomised per pair, scores and file names hidden, "
                    "question: which sounds more like Somali qaraami; 'neither' allowed",
        "pairs": pairs_out,
        "summary": {"n": n, **counts, "adapter_rate": round(counts["adapter"] / n, 4) if n else None,
                    "wilson95": [round(lo, 4), round(hi, 4)]},
    }
    LISTENING.mkdir(parents=True, exist_ok=True)
    out = LISTENING / f"{s.name}_{listener}_{dt.datetime.now().strftime('%Y%m%d-%H%M%S')}.json"
    out.write_text(json.dumps(result, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return result, out


def render_result(result: dict, path: Path) -> str:
    sm = result["summary"]
    rows = "".join(
        f'<tr><td class="n">{p["pair"]:03d}</td><td class="cap">{esc(p["caption"])}</td><td>{esc(p["A"])}</td>'
        f'<td>{esc(p["chosen"])}</td><td><b>{esc(p["preferred"])}</b></td><td>{esc(p["note"])}</td></tr>'
        for p in result["pairs"])
    try:
        rel = path.relative_to(REPO)
    except ValueError:
        rel = path
    return f"""<div class="result"><h2 style="margin-top:0">Result: adapter preferred in {sm["adapter"]} of {sm["n"]} pairs
(base {sm["base"]}, neither {sm["none"]}); adapter rate {sm["adapter_rate"]:.2f}, 95% Wilson interval
[{sm["wilson95"][0]:.2f}, {sm["wilson95"][1]:.2f}]</h2>
<p class="note">Saved to {esc(rel)}. Rebuild the demo page to include it. Reload this page for a fresh, re-randomised session.</p></div>
<table><tr><th>#</th><th>caption</th><th>A was</th><th>you chose</th><th>preferred</th><th>note</th></tr>{rows}</table>"""


# ------------------------------------------------------------------- server

class Handler(BaseHTTPRequestHandler):
    sets: dict[str, ListeningSet] = {}
    page: bytes = b""

    def log_message(self, fmt: str, *args) -> None:  # quiet by default
        if "--verbose" in sys.argv:
            super().log_message(fmt, *args)

    def send_html(self, body: str, status: int = 200) -> None:
        data = body.encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(data)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(data)

    def do_GET(self) -> None:
        path = urlparse(self.path).path
        if path in ("/", "/index.html"):
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(self.page)))
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            self.wfile.write(self.page)
            return
        m = re.match(r"^/test/([A-Za-z0-9_]+)$", path)
        if m and m.group(1) in self.sets and self.sets[m.group(1)].testable:
            s = self.sets[m.group(1)]
            self.send_html(render_test(s, new_session(s)))
            return
        m = re.match(r"^/blind/([A-Za-z0-9_-]+)/(\d+)/([AB])\.wav$", path)
        if m and m.group(1) in SESSIONS:
            sess = SESSIONS[m.group(1)]
            s = self.sets[sess["set"]]
            i = int(m.group(2))
            pair = next((p for p in s.pairs if p.index == i), None)
            if pair is None or i not in sess["order"]:
                self.send_error(404)
                return
            adapter_is_a = sess["order"][i]
            clip = pair.adapter if (m.group(3) == "A") == adapter_is_a else pair.base
            self.send_wav(s.dir / clip.file)
            return
        m = re.match(r"^/audio/([A-Za-z0-9_]+)/([A-Za-z0-9_]+\.wav)$", path)
        if not m or m.group(1) not in self.sets:
            self.send_error(404)
            return
        d = self.sets[m.group(1)].dir
        f = (d / m.group(2)).resolve()
        if f.parent != d.resolve() or not WAV_NAME.match(f.name) or not f.is_file():
            self.send_error(404)
            return
        self.send_wav(f)

    def do_POST(self) -> None:
        m = re.match(r"^/submit/([A-Za-z0-9_-]+)$", urlparse(self.path).path)
        if not m or m.group(1) not in SESSIONS:
            self.send_error(404)
            return
        length = int(self.headers.get("Content-Length") or 0)
        if length > 200_000:
            self.send_error(413)
            return
        try:
            payload = json.loads(self.rfile.read(length) or b"{}")
        except json.JSONDecodeError:
            self.send_error(400)
            return
        s = self.sets[SESSIONS[m.group(1)]["set"]]
        result, path = save_result(s, m.group(1), payload)
        del SESSIONS[m.group(1)]
        self.send_html(render_result(result, path))

    def send_wav(self, f: Path) -> None:
        size = f.stat().st_size
        start, end = 0, size - 1
        rng = self.headers.get("Range")
        partial = False
        if rng:
            m = re.match(r"bytes=(\d*)-(\d*)$", rng.strip())
            if m:
                if m.group(1):
                    start = int(m.group(1))
                    if m.group(2):
                        end = min(int(m.group(2)), size - 1)
                elif m.group(2):
                    start = max(size - int(m.group(2)), 0)
                if start > end or start >= size:
                    self.send_response(416)
                    self.send_header("Content-Range", f"bytes */{size}")
                    self.end_headers()
                    return
                partial = True
        length = end - start + 1
        self.send_response(206 if partial else 200)
        self.send_header("Content-Type", "audio/wav")
        self.send_header("Accept-Ranges", "bytes")
        self.send_header("Content-Length", str(length))
        if partial:
            self.send_header("Content-Range", f"bytes {start}-{end}/{size}")
        self.end_headers()
        with f.open("rb") as fh:
            fh.seek(start)
            remaining = length
            while remaining > 0:
                chunk = fh.read(min(65536, remaining))
                if not chunk:
                    break
                self.wfile.write(chunk)
                remaining -= len(chunk)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--port", type=int, default=8777)
    ap.add_argument("--open", action="store_true", help="open the page in the default browser")
    ap.add_argument("--verbose", action="store_true", help="log every request")
    args = ap.parse_args()

    sets = load_sets()
    if not sets:
        sys.exit(f"no listening sets found under {DATA}")
    Handler.sets = {s.name: s for s in sets}
    Handler.page = render(sets).encode("utf-8")
    for s in sets:
        print(f"{s.name:24s} {len(s.pairs):3d} pairs  {s.dir.relative_to(REPO)}{'  (blind test available)' if s.testable else ''}")

    url = f"http://127.0.0.1:{args.port}/"
    server = ThreadingHTTPServer(("127.0.0.1", args.port), Handler)
    print(f"listening on {url}  (Ctrl-C to stop); results -> {LISTENING}")
    if args.open:
        webbrowser.open(url)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
