"""Serve the A/B listening sets on loopback so they can be heard side by side.

The listening test is the arbiter for every adapter in the programme, and the
sets already exist on disk: the same seeded captions generated by a base model
and by its adapter. This page puts them next to each other with the scores that
were computed when they were generated, so the comparison is heard on the same
prompts and read off the same numbers.

Sets picked up when present:
  data/ab_<tag>/               pairNNN_{base,adapter}.wav + runs/qaraami_<tag>_r32/eval_<tag>.json
  data/oud_ab_listening/       pairNNN_{base,finetuned}.wav + data/eval_pcs/oud_{base,lora500}.csv
  data/harvard_ab_listening/   pairNNN_{base,finetuned}.wav + data/eval_pcs/harvard_{base,lora1500}.csv
  data/ab_melody/              melodyNNN_base.wav + melody_condition.json

Binds 127.0.0.1 only. Serves nothing but these generated clips; source audio is
never on this page. Stdlib only.

Usage (from the repo root):
  python apps/ai-service/scripts/ab_listen.py            # http://127.0.0.1:8777
  python apps/ai-service/scripts/ab_listen.py --open     # and open it in the browser
"""
from __future__ import annotations

import argparse
import csv
import html
import json
import re
import sys
import webbrowser
from dataclasses import dataclass, field
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
DATA = REPO / "data"
RUNS = REPO / "runs"
WAV_NAME = re.compile(r"^[A-Za-z0-9_]+\.wav$")
PAIR = re.compile(r"pair(\d{3})_(base|adapter|finetuned)\.wav$")


@dataclass
class Clip:
    file: str
    pcs: float | None = None
    voiced: float | None = None
    tonic: str | None = None
    tuning: float | None = None


@dataclass
class Pair:
    index: int
    caption: str
    base: Clip | None = None
    adapter: Clip | None = None


@dataclass
class ListeningSet:
    name: str          # URL segment and directory name under data/
    title: str
    dir: Path
    note: str = ""
    pairs: list[Pair] = field(default_factory=list)
    summary: dict = field(default_factory=dict)


def read_captions(d: Path) -> dict[int, str]:
    out: dict[int, str] = {}
    p = d / "CAPTIONS.txt"
    if not p.exists():
        return out
    for line in p.read_text().splitlines():
        m = re.match(r"pair(\d{3}):\s*(.*)", line)
        if m:
            out[int(m.group(1))] = m.group(2).strip()
    return out


def scan_pairs(d: Path) -> dict[int, Pair]:
    captions = read_captions(d)
    pairs: dict[int, Pair] = {}
    for f in sorted(d.glob("pair*.wav")):
        m = PAIR.search(f.name)
        if not m:
            continue
        i = int(m.group(1))
        pair = pairs.setdefault(i, Pair(i, captions.get(i, "")))
        clip = Clip(f.name)
        if m.group(2) == "base":
            pair.base = clip
        else:
            pair.adapter = clip
    return pairs


def scale_set(tag: str) -> ListeningSet | None:
    d = DATA / f"ab_{tag}"
    ev = RUNS / f"qaraami_{tag}_r32" / f"eval_{tag}.json"
    if not d.is_dir():
        return None
    s = ListeningSet(f"ab_{tag}", f"MusicGen-{tag}", d)
    pairs = scan_pairs(d)
    if ev.exists():
        e = json.loads(ev.read_text())
        ce = e["per_song_ce"]
        imp = ce["improvement_base_minus_adapter"]
        s.summary = {
            "model": e["model"],
            "best_ckpt": e["best_ckpt"],
            "songs": ce["n_songs"],
            "ce_base": ce["base"]["mean"],
            "ce_adapter": ce["adapter"]["mean"],
            "ce_gain": imp["mean"],
            "ce_ci": imp["ci95"],
            "significant": imp["significant"],
            "pcs_base": e["ab"]["base"]["pcs_mean"],
            "pcs_adapter": e["ab"]["adapter"]["pcs_mean"],
            "voiced_base": e["ab"]["base"]["voiced_fraction_mean"],
            "voiced_adapter": e["ab"]["adapter"]["voiced_fraction_mean"],
        }
        for row in e["ab"]["pairs"]:
            pair = pairs.get(row["pair"])
            if pair is None:
                continue
            if not pair.caption:
                pair.caption = row.get("caption", "")
            for side in ("base", "adapter"):
                clip = getattr(pair, side)
                sc = row.get(side) or {}
                if clip and sc.get("scored"):
                    clip.pcs = sc.get("pcs")
                    clip.voiced = sc.get("voiced_fraction")
                    clip.tonic = sc.get("tonic")
                    clip.tuning = sc.get("tuning_offset_cents")
        s.note = f"{e['model']}, best checkpoint {e['best_ckpt']}; same 16 captions and seeds as every other scale set."
    s.pairs = [pairs[i] for i in sorted(pairs)]
    return s


def pcs_csv(name: str) -> dict[int, dict]:
    """Per-clip scores from data/eval_pcs/<name>.csv keyed by pair index.

    The scorer names clips gen_NNN in the order they were generated, which is
    the pair order of the listening set; pairNNN is accepted too.
    """
    p = DATA / "eval_pcs" / f"{name}.csv"
    out: dict[int, dict] = {}
    if not p.exists():
        return out
    with p.open() as fh:
        for row in csv.DictReader(fh):
            m = re.search(r"(?:pair|gen_)(\d{3})", str(row.get("clip", "")))
            if m:
                out[int(m.group(1))] = row
    return out


def _num(row: dict, *keys: str) -> float | None:
    for k in keys:
        if k in row and row[k] not in ("", None):
            try:
                return float(row[k])
            except ValueError:
                pass
    return None


def legacy_set(name: str, title: str, base_group: str, ft_group: str, note: str) -> ListeningSet | None:
    d = DATA / name
    if not d.is_dir():
        return None
    s = ListeningSet(name, title, d, note)
    pairs = scan_pairs(d)
    for side, group in (("base", base_group), ("adapter", ft_group)):
        rows = pcs_csv(group)
        for i, row in rows.items():
            clip = getattr(pairs.get(i), side, None) if i in pairs else None
            if clip:
                clip.pcs = _num(row, "pcs", "pcs_score")
                clip.voiced = _num(row, "voiced_fraction", "voiced")
                clip.tonic = row.get("tonic") or None
                clip.tuning = _num(row, "tuning_offset_cents", "tuning_offset")
    for group, key in ((base_group, "base"), (ft_group, "adapter")):
        j = DATA / "eval_pcs" / f"{group}.json"
        if j.exists():
            g = json.loads(j.read_text())
            s.summary[f"pcs_{key}"] = g.get("pcs_mean")
            s.summary[f"voiced_{key}"] = g.get("voiced_fraction_mean")
    s.pairs = [pairs[i] for i in sorted(pairs)]
    return s


def melody_set() -> ListeningSet | None:
    d = DATA / "ab_melody"
    j = d / "melody_condition.json"
    if not d.is_dir():
        return None
    s = ListeningSet("ab_melody", "musicgen-melody, conditioned on real qaraami melodies", d)
    if j.exists():
        e = json.loads(j.read_text())
        s.note = (f"{e['model']}, no adapter, one caption: \"{e['caption']}\". "
                  f"Each clip follows the chroma of a held-out qaraami clip (named per row). "
                  f"Mean PCS {e['pcs_mean']:.3f}, voiced fraction {e['voiced_fraction_mean']:.3f}.")
        for c in e.get("clips", []):
            s.pairs.append(Pair(c["i"], f"melody from {c['ref']}",
                                base=Clip(c["file"], c.get("pcs"), c.get("voiced_fraction"))))
    else:
        for i, f in enumerate(sorted(d.glob("melody*_base.wav"))):
            s.pairs.append(Pair(i, "", base=Clip(f.name)))
    return s


def load_sets() -> list[ListeningSet]:
    sets: list[ListeningSet] = []
    for tag in ("medium", "large"):
        s = scale_set(tag)
        if s:
            sets.append(s)
    s = legacy_set("oud_ab_listening", "MusicGen-small, oud adapter (step 500)", "oud_base", "oud_lora500",
                   "8 seeded oud captions, base vs the oud adapter; 10 s clips.")
    if s:
        sets.append(s)
    s = legacy_set("harvard_ab_listening", "MusicGen-small, harvard_raw adapter (step 1500)", "harvard_base",
                   "harvard_lora1500", "8 seeded Harvard test captions, base vs the harvard_raw adapter; 10 s clips.")
    if s:
        sets.append(s)
    s = melody_set()
    if s:
        sets.append(s)
    return sets


# ---------------------------------------------------------------- rendering

CSS = """
:root{--bg:#0C0B14;--panel:#15131f;--line:#2a2738;--ink:#ece7dc;--dim:#9a94a8;--accent:#C89B5F}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.45 Nunito,-apple-system,Helvetica,Arial,sans-serif}
main{max-width:1500px;margin:0 auto;padding:28px 24px 80px}
h1{font:600 28px/1.2 "Playfair Display",Georgia,serif;margin:0 0 6px}
h1 span{color:var(--accent)}
h2{font:600 20px/1.2 "Playfair Display",Georgia,serif;margin:36px 0 6px}
p.note{color:var(--dim);margin:0 0 14px}
table{border-collapse:collapse;width:100%;background:var(--panel);border:1px solid var(--line)}
th,td{border-top:1px solid var(--line);padding:8px 10px;text-align:left;vertical-align:top}
th{color:var(--dim);font-weight:600;font-size:13px}
td.n{color:var(--dim);white-space:nowrap}
td.cap{max-width:380px;color:var(--ink)}
td.clip{min-width:230px}
audio{width:100%;height:32px;display:block}
.score{color:var(--dim);font-size:12.5px;margin-top:4px;white-space:nowrap}
.score b{color:var(--ink);font-weight:600}
.up{color:#8fd19e}.down{color:#e39a8b}
.summary td,.summary th{white-space:nowrap}
.rights{margin-top:40px;color:var(--dim);font-size:13px;border-top:1px solid var(--line);padding-top:12px}
"""

JS = """
document.addEventListener('play', e => {
  for (const a of document.querySelectorAll('audio')) if (a !== e.target) a.pause();
}, true);
"""


def esc(s: object) -> str:
    return html.escape(str(s))


def fmt(x: float | None, nd: int = 3) -> str:
    return "–" if x is None else f"{x:.{nd}f}"


def clip_cell(setname: str, clip: Clip | None) -> str:
    if clip is None:
        return '<td class="clip">–</td>'
    score = ""
    if clip.pcs is not None or clip.voiced is not None:
        parts = [f"PCS <b>{fmt(clip.pcs)}</b>", f"voiced <b>{fmt(clip.voiced)}</b>"]
        if clip.tonic:
            parts.append(f"tonic {esc(clip.tonic)}")
        if clip.tuning is not None:
            parts.append(f"{clip.tuning:+.0f} c")
        score = f'<div class="score">{" · ".join(parts)}</div>'
    src = f"/audio/{setname}/{clip.file}"
    return f'<td class="clip"><audio controls preload="none" src="{esc(src)}"></audio>{score}</td>'


def delta(a: float | None, b: float | None, nd: int = 3) -> str:
    if a is None or b is None:
        return "–"
    d = b - a
    cls = "up" if d > 0 else "down" if d < 0 else ""
    return f'<span class="{cls}">{d:+.{nd}f}</span>'


def render_scale_summary(sets: list[ListeningSet]) -> str:
    rows = [s for s in sets if s.summary.get("ce_gain") is not None]
    if not rows:
        return ""
    out = ['<h2>Scale runs, held-out numbers</h2>',
           '<p class="note">Per-song test cross-entropy on unseen songs with a bootstrap 95% CI over songs; '
           'PCS and voiced fraction are means over the 16-clip A/B set below. Lower CE is better; '
           'voiced fraction is the share of frames with a trackable pitch.</p>',
           '<table class="summary"><tr><th>model</th><th>best ckpt</th><th>songs</th>'
           '<th>CE base → adapter</th><th>gain (nats), 95% CI</th>'
           '<th>PCS base → adapter</th><th>voiced base → adapter</th></tr>']
    for s in rows:
        m = s.summary
        sig = "significant" if m["significant"] else "not significant"
        out.append(
            f'<tr><td>{esc(m["model"])}</td><td>{esc(m["best_ckpt"])}</td><td>{m["songs"]}</td>'
            f'<td>{m["ce_base"]:.4f} → <b>{m["ce_adapter"]:.4f}</b></td>'
            f'<td>+{m["ce_gain"]:.3f} [{m["ce_ci"][0]:.3f}, {m["ce_ci"][1]:.3f}], {sig}</td>'
            f'<td>{m["pcs_base"]:.3f} → {m["pcs_adapter"]:.3f} ({delta(m["pcs_base"], m["pcs_adapter"])})</td>'
            f'<td>{m["voiced_base"]:.3f} → {m["voiced_adapter"]:.3f} ({delta(m["voiced_base"], m["voiced_adapter"])})</td></tr>')
    out.append('</table>')
    return "\n".join(out)


def render_side_by_side(sets: list[ListeningSet]) -> str:
    """Scale sets share captions and seeds, so one row per caption with every model across."""
    scale = [s for s in sets if s.name.startswith("ab_") and s.name != "ab_melody"]
    if not scale:
        return ""
    n = max(len(s.pairs) for s in scale)
    out = ['<h2>Same prompt, same seed, every size</h2>',
           '<p class="note">Left to right within each model: base, then adapter. '
           'Playing a clip pauses the others.</p>',
           '<table><tr><th>#</th><th>caption</th>']
    for s in scale:
        out.append(f'<th>{esc(s.title)} · base</th><th>{esc(s.title)} · adapter</th>')
    out.append('</tr>')
    for i in range(n):
        caption = next((s.pairs[i].caption for s in scale if i < len(s.pairs) and s.pairs[i].caption), "")
        out.append(f'<tr><td class="n">{i:03d}</td><td class="cap">{esc(caption)}</td>')
        for s in scale:
            pair = s.pairs[i] if i < len(s.pairs) else None
            out.append(clip_cell(s.name, pair.base if pair else None))
            out.append(clip_cell(s.name, pair.adapter if pair else None))
        out.append('</tr>')
    out.append('</table>')
    return "\n".join(out)


def render_set(s: ListeningSet) -> str:
    out = [f'<h2>{esc(s.title)}</h2>']
    if s.note:
        out.append(f'<p class="note">{esc(s.note)}</p>')
    sm = s.summary
    if sm.get("pcs_base") is not None and sm.get("pcs_adapter") is not None:
        out.append(f'<p class="note">Set means: PCS {fmt(sm["pcs_base"])} → {fmt(sm["pcs_adapter"])} '
                   f'({delta(sm["pcs_base"], sm["pcs_adapter"])}), voiced fraction '
                   f'{fmt(sm.get("voiced_base"))} → {fmt(sm.get("voiced_adapter"))} '
                   f'({delta(sm.get("voiced_base"), sm.get("voiced_adapter"))}).</p>')
    two_sided = any(p.adapter for p in s.pairs)
    out.append('<table><tr><th>#</th><th>caption</th><th>base</th>' + ('<th>adapter</th>' if two_sided else '') + '</tr>')
    for p in s.pairs:
        out.append(f'<tr><td class="n">{p.index:03d}</td><td class="cap">{esc(p.caption)}</td>')
        out.append(clip_cell(s.name, p.base))
        if two_sided:
            out.append(clip_cell(s.name, p.adapter))
        out.append('</tr>')
    out.append('</table>')
    return "\n".join(out)


def render(sets: list[ListeningSet]) -> str:
    body = [render_scale_summary(sets), render_side_by_side(sets)]
    for s in sets:
        if s.name in ("ab_medium", "ab_large"):
            continue
        body.append(render_set(s))
    n_clips = sum((1 if p.base else 0) + (1 if p.adapter else 0) for s in sets for p in s.pairs)
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>QaraamiGen listening sets</title><style>{CSS}</style></head><body><main>
<h1>Qaraami<span>Gen</span> — listening sets</h1>
<p class="note">{len(sets)} sets, {n_clips} clips, all generated by the models named on each section.
Served from this machine only (127.0.0.1).</p>
{"".join(body)}
<div class="rights">Every clip on this page is model output. The adapters were trained on recordings
that are not distributed and are not served here.</div>
</main><script>{JS}</script></body></html>"""


# ------------------------------------------------------------------- server

class Handler(BaseHTTPRequestHandler):
    sets: dict[str, ListeningSet] = {}
    page: bytes = b""

    def log_message(self, fmt: str, *args) -> None:  # quiet by default
        if "--verbose" in sys.argv:
            super().log_message(fmt, *args)

    def do_GET(self) -> None:
        if self.path in ("/", "/index.html"):
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(self.page)))
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            self.wfile.write(self.page)
            return
        m = re.match(r"^/audio/([A-Za-z0-9_]+)/([A-Za-z0-9_]+\.wav)$", self.path)
        if not m or m.group(1) not in self.sets:
            self.send_error(404)
            return
        d = self.sets[m.group(1)].dir
        f = (d / m.group(2)).resolve()
        if f.parent != d.resolve() or not WAV_NAME.match(f.name) or not f.is_file():
            self.send_error(404)
            return
        self.send_wav(f)

    def send_wav(self, f: Path) -> None:
        size = f.stat().st_size
        start, end = 0, size - 1
        rng = self.headers.get("Range")
        partial = False
        if rng:
            m = re.match(r"bytes=(\d*)-(\d*)$", rng.strip())
            if m:
                if m.group(1):
                    start = int(m.group(1))
                    if m.group(2):
                        end = min(int(m.group(2)), size - 1)
                elif m.group(2):
                    start = max(size - int(m.group(2)), 0)
                if start > end or start >= size:
                    self.send_response(416)
                    self.send_header("Content-Range", f"bytes */{size}")
                    self.end_headers()
                    return
                partial = True
        length = end - start + 1
        self.send_response(206 if partial else 200)
        self.send_header("Content-Type", "audio/wav")
        self.send_header("Accept-Ranges", "bytes")
        self.send_header("Content-Length", str(length))
        if partial:
            self.send_header("Content-Range", f"bytes {start}-{end}/{size}")
        self.end_headers()
        with f.open("rb") as fh:
            fh.seek(start)
            remaining = length
            while remaining > 0:
                chunk = fh.read(min(65536, remaining))
                if not chunk:
                    break
                self.wfile.write(chunk)
                remaining -= len(chunk)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--port", type=int, default=8777)
    ap.add_argument("--open", action="store_true", help="open the page in the default browser")
    ap.add_argument("--verbose", action="store_true", help="log every request")
    args = ap.parse_args()

    sets = load_sets()
    if not sets:
        sys.exit(f"no listening sets found under {DATA}")
    Handler.sets = {s.name: s for s in sets}
    Handler.page = render(sets).encode("utf-8")
    for s in sets:
        print(f"{s.name:24s} {len(s.pairs):3d} pairs  {s.dir.relative_to(REPO)}")

    url = f"http://127.0.0.1:{args.port}/"
    server = ThreadingHTTPServer(("127.0.0.1", args.port), Handler)
    print(f"listening on {url}  (Ctrl-C to stop)")
    if args.open:
        webbrowser.open(url)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
