"""Build the shareable QaraamiGen demo page from the run artifacts on disk.

A plain academic page in the style of a research group's demo index: prose,
tables, figures and inline audio players, base model against adapter on the
same prompt and seed. Every number comes from the eval JSON, run configs and
scorer CSVs; every clip is model output already generated by the evaluation
scripts. Nothing is generated or scored here, so the page cannot disagree with
the reports.

Outputs (docs/demo/site/):
  index.html            relative links into audio/ and figures/  (tracked)
  audio/*.mp3           transcoded from the A/B wavs, 96 kb/s mono  (ignored)
  figures/*.png         copied from docs/figures                    (ignored)
  QaraamiGen-demo.html  single self-contained file, audio and figures
                        inlined as data URIs; the thing to send      (ignored)

Also writes docs/figures/ft7_scale_val_curves.{png,svg} (validation CE per
checkpoint for the medium and large runs, from runs/qaraami_*_r32/loss.csv).

Clip selection is fixed by rule, not by ear: the four synthetic qaraami prompts
and the first four catalogue prompts of the 16-prompt scale A/B set; the first
four pairs of each small-model set; the three melody-conditioned clips with the
highest voiced fraction; the large run's per-checkpoint sample at steps 250,
1000, 2000 and the best checkpoint. Catalogue prompts carry performer credits
from the Harvard finding aid; those are omitted from the displayed captions.

Usage (from the repo root, the musicgen env has matplotlib):
  ~/ai/musicgen-env/bin/python apps/ai-service/scripts/build_demo_page.py
"""
from __future__ import annotations

import base64
import csv
import datetime as dt
import html
import json
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
DATA = REPO / "data"
RUNS = REPO / "runs"
FIG = REPO / "docs/figures"
OUT = REPO / "docs/demo/site"
AUDIO = OUT / "audio"
FIGOUT = OUT / "figures"

SCALE_PAIRS = [0, 1, 2, 3, 4, 8, 10, 11]
SMALL_PAIRS = [0, 1, 2, 3]
PROGRESSION_STEPS = [250, 1000, 2000]  # plus the best checkpoint, read from eval
N_MELODY = 3
MP3_KBPS = 96
CONTACT = "research@somalimusicarchive.com"

# MusicGen-small results, docs/eval/EVALUATION.md T1 and T4 (generated by eval_report.py).
SMALL = {
    "oud": {
        "title": "oud adapter",
        "corpus": "private oud (kaban) qaraami collection, 28 songs",
        "val": (4.5132, 4.4785), "test": (2.6302, 2.6092), "best": "step 500 of 1,000",
        "set": "oud_ab_listening", "csv": ("oud_base", "oud_lora500"),
        "real": {"pcs": 0.914, "voiced": 0.435},
    },
    "harvard_raw": {
        "title": "harvard_raw adapter",
        "corpus": "Maryan “Aryette” Omar Ali Collection, Harvard AWM Spec Coll 103, 119 tracks",
        "val": (4.6262, 4.5501), "test": (4.8363, 4.7468), "best": "step 2,750 of 3,000",
        "set": "harvard_ab_listening", "csv": ("harvard_base", "harvard_lora1500"),
        "real": {"pcs": 0.847, "voiced": 0.530},
    },
}
PARAMS = {"small": "0.59 B", "medium": "1.5 B", "large": "3.3 B"}
TRAINABLE = {"medium": "61.3 M", "large": "81.8 M"}
STEP_RATE = {"medium": "~10 s", "large": "~16 s"}
PEAK_MEM = {"medium": "11.3 GB", "large": "16.3 GB"}


@dataclass
class Clip:
    src: Path
    name: str            # output basename without extension
    pcs: float | None = None
    voiced: float | None = None

    @property
    def rel(self) -> str:
        return f"audio/{self.name}.mp3"


# ------------------------------------------------------------------ inputs

def strip_credit(caption: str) -> str:
    return re.sub(r",\s*performed by .*$", "", caption).strip()


def read_captions(d: Path) -> dict[int, str]:
    out: dict[int, str] = {}
    for line in (d / "CAPTIONS.txt").read_text().splitlines():
        m = re.match(r"pair(\d{3}):\s*(.*)", line)
        if m:
            out[int(m.group(1))] = m.group(2).strip()
    return out


def pcs_csv(name: str) -> dict[int, dict]:
    out: dict[int, dict] = {}
    with (DATA / "eval_pcs" / f"{name}.csv").open() as fh:
        for row in csv.DictReader(fh):
            m = re.search(r"(?:pair|gen_)(\d{3})", row.get("clip", ""))
            if m:
                out[int(m.group(1))] = row
    return out


def num(x) -> float | None:
    try:
        return float(x)
    except (TypeError, ValueError):
        return None


def load_scale(tag: str) -> dict:
    e = json.loads((RUNS / f"qaraami_{tag}_r32" / f"eval_{tag}.json").read_text())
    cfg = json.loads((RUNS / f"qaraami_{tag}_r32" / "config.json").read_text())
    steps, vals = [], []
    with (RUNS / f"qaraami_{tag}_r32" / "loss.csv").open() as fh:
        for row in csv.DictReader(fh):
            if row["val_loss"]:
                steps.append(int(row["step"]))
                vals.append(float(row["val_loss"]))
    return {"eval": e, "cfg": cfg, "val_curve": (steps, vals)}


def split_counts() -> dict:
    clips: dict[str, int] = {}
    songs: dict[str, set] = {}
    hours = 0.0
    for line in (DATA / "scale_captions.jsonl").open():
        d = json.loads(line)
        clips[d["split"]] = clips.get(d["split"], 0) + 1
        songs.setdefault(d["split"], set()).add(d["song_sha256"])
    all_songs = set().union(*songs.values())
    return {"clips": clips, "songs": {k: len(v) for k, v in songs.items()},
            "total_clips": sum(clips.values()), "total_songs": len(all_songs)}


# ---------------------------------------------------------------- transcode

def transcode(clips: list[Clip]) -> None:
    AUDIO.mkdir(parents=True, exist_ok=True)
    for c in clips:
        dst = AUDIO / f"{c.name}.mp3"
        if dst.exists() and dst.stat().st_mtime >= c.src.stat().st_mtime:
            continue
        subprocess.run(
            ["ffmpeg", "-v", "error", "-y", "-i", str(c.src), "-ac", "1", "-ar", "32000",
             "-codec:a", "libmp3lame", "-b:a", f"{MP3_KBPS}k", "-id3v2_version", "0", str(dst)],
            check=True)


# ------------------------------------------------------------------ figure

def figure_scale_val(curves: dict[str, tuple[list[int], list[float]]]) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    plt.rcParams.update({"figure.dpi": 150, "font.size": 9, "axes.spines.top": False,
                         "axes.spines.right": False, "font.family": "sans-serif"})
    colors = {"medium": "#2f6fb0", "large": "#c8843a"}   # validated pair, light surface
    fig, ax = plt.subplots(figsize=(7.4, 3.6))
    xmax = max(s[-1] for s, _ in curves.values())
    for tag, (steps, vals) in curves.items():
        ax.hlines(vals[0], -60, xmax, color=colors[tag], lw=1, ls=(0, (1, 3)), alpha=0.8)
        ax.plot(steps, vals, color=colors[tag], lw=2, marker="o", ms=4,
                solid_joinstyle="round", solid_capstyle="round", label=f"MusicGen-{tag}, LoRA r32")
        ax.text(xmax + 60, vals[0], f"base {vals[0]:.4f}", va="center", fontsize=7.5, color="#666")
        ax.text(xmax + 60, vals[-1], f"{vals[-1]:.4f}", va="center", fontsize=8, color="#222")
    ax.set_xlim(-60, xmax + 520)
    ax.set_xlabel("optimizer step")
    ax.set_ylabel("validation token cross-entropy (nats)")
    ax.set_title("Validation cross-entropy per checkpoint; dotted lines are each model's base", fontsize=9)
    ax.grid(axis="y", color="#e6e6e6", lw=0.8)
    ax.set_axisbelow(True)
    ax.legend(frameon=False, fontsize=8, loc="center right")
    fig.tight_layout()
    fig.savefig(FIG / "ft7_scale_val_curves.png")
    fig.savefig(FIG / "ft7_scale_val_curves.svg")
    plt.close(fig)


# ------------------------------------------------------------------- html

def esc(s: object) -> str:
    return html.escape(str(s))


def f3(x: float | None) -> str:
    return "–" if x is None else f"{x:.3f}"


def f4(x: float) -> str:
    return f"{x:.4f}"


def player(c: Clip | None, scored: bool = True) -> str:
    if c is None:
        return "<td>–</td>"
    s = ""
    if scored and (c.pcs is not None or c.voiced is not None):
        s = f'<div class="score">PCS {f3(c.pcs)} · voiced {f3(c.voiced)}</div>'
    return f'<td class="clip"><audio controls preload="none" src="{esc(c.rel)}"></audio>{s}</td>'


def delta(a: float, b: float) -> str:
    return f"{b - a:+.3f}"


def build_html(ctx: dict) -> str:
    m, lg = ctx["scale"]["medium"], ctx["scale"]["large"]
    em, el = m["eval"], lg["eval"]
    sc = ctx["splits"]
    today = dt.date.today().strftime("%B %Y")

    def ce(e):
        c = e["per_song_ce"]
        i = c["improvement_base_minus_adapter"]
        return c["base"]["mean"], c["adapter"]["mean"], i["mean"], i["ci95"], c["n_songs"]

    # ---- listen: scale table
    rows = []
    for i in SCALE_PAIRS:
        cap = strip_credit(ctx["scale_captions"][i])
        cells = "".join(player(ctx["clips"][f"{tag}_{i:03d}_{side}"])
                        for tag in ("medium", "large") for side in ("base", "adapter"))
        rows.append(f'<tr><td class="cap">{esc(cap)}</td>{cells}</tr>')
    scale_table = (
        '<table class="ab"><thead><tr><th>prompt (held-out test caption)</th>'
        '<th>medium, base</th><th>medium, adapter</th><th>large, base</th><th>large, adapter</th></tr></thead>'
        f'<tbody>{"".join(rows)}</tbody></table>')

    # ---- listen: small tables
    small_tables = []
    for key, info in SMALL.items():
        caps = ctx["small_captions"][key]
        rows = []
        for i in SMALL_PAIRS:
            rows.append(f'<tr><td class="cap">{esc(strip_credit(caps[i]))}</td>'
                        f'{player(ctx["clips"][f"{key}_{i:03d}_base"])}{player(ctx["clips"][f"{key}_{i:03d}_adapter"])}</tr>')
        small_tables.append(
            f'<h4>{esc(info["title"])} — {esc(info["corpus"])}</h4>'
            '<table class="ab"><thead><tr><th>prompt</th><th>base</th><th>adapter</th></tr></thead>'
            f'<tbody>{"".join(rows)}</tbody></table>')

    # ---- listen: progression
    prog_cells = "".join(
        f'<td class="clip"><div class="lab">step {s:,}{" (best)" if s == ctx["best_step"] else ""}</div>'
        f'<audio controls preload="none" src="{esc(ctx["clips"][f"large_step{s:04d}"].rel)}"></audio></td>'
        for s in ctx["prog_steps"])
    prog_table = f'<table class="ab"><tbody><tr>{prog_cells}</tr></tbody></table>'

    # ---- listen: melody
    mel_cells = "".join(player(c) for c in ctx["melody_clips"])
    mel_table = f'<table class="ab"><tbody><tr>{mel_cells}</tr></tbody></table>'

    # ---- results tables
    def scale_row(tag, d):
        e = d["eval"]
        b, a, g, ci, n = ce(e)
        ab = e["ab"]
        return (f'<tr><td>MusicGen-{tag}</td><td>{PARAMS[tag]}</td><td>{TRAINABLE[tag]}</td>'
                f'<td>{esc(e["best_ckpt"].replace("ckpt_step_", "step "))}</td>'
                f'<td>{f4(b)} → <b>{f4(a)}</b></td><td>+{g:.3f} [{ci[0]:.3f}, {ci[1]:.3f}]</td>'
                f'<td>{f3(ab["base"]["pcs_mean"])} → {f3(ab["adapter"]["pcs_mean"])} ({delta(ab["base"]["pcs_mean"], ab["adapter"]["pcs_mean"])})</td>'
                f'<td>{f3(ab["base"]["voiced_fraction_mean"])} → {f3(ab["adapter"]["voiced_fraction_mean"])} ({delta(ab["base"]["voiced_fraction_mean"], ab["adapter"]["voiced_fraction_mean"])})</td></tr>')

    scale_results = (
        '<table><thead><tr><th>model</th><th>params</th><th>LoRA params</th><th>best ckpt</th>'
        '<th>per-song test CE, base → adapter</th><th>gain (nats), 95% CI</th>'
        '<th>PCS, base → adapter</th><th>voiced fraction, base → adapter</th></tr></thead>'
        f'<tbody>{scale_row("medium", m)}{scale_row("large", lg)}</tbody></table>')

    def small_row(key, info):
        s = ctx["small_summary"][key]
        return (f'<tr><td>{esc(info["title"])}</td><td>{esc(info["corpus"])}</td><td>{esc(info["best"])}</td>'
                f'<td>{f4(info["val"][0])} → <b>{f4(info["val"][1])}</b></td>'
                f'<td>{f4(info["test"][0])} → <b>{f4(info["test"][1])}</b></td>'
                f'<td>{f3(s["pcs_base"])} → {f3(s["pcs_adapter"])} (real clips {f3(info["real"]["pcs"])})</td>'
                f'<td>{f3(s["voiced_base"])} → {f3(s["voiced_adapter"])} (real clips {f3(info["real"]["voiced"])})</td></tr>')

    small_results = (
        '<table><thead><tr><th>adapter</th><th>corpus</th><th>best ckpt</th><th>val CE</th>'
        '<th>test CE (unseen songs)</th><th>PCS, base → adapter</th><th>voiced fraction, base → adapter</th></tr></thead>'
        f'<tbody>{"".join(small_row(k, v) for k, v in SMALL.items())}</tbody></table>')

    mb, ma, mg, mci, mn = ce(em)
    lb, la, lgn, lci, ln = ce(el)
    cfg = lg["cfg"]

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>QaraamiGen — adapting a text-to-music model to Somali qaraami</title>
<style>
body{{margin:0;background:#fff;color:#1b1b1b;font:16px/1.55 Charter,"Iowan Old Style","Palatino Linotype",Georgia,serif}}
main{{max-width:940px;margin:0 auto;padding:44px 28px 80px}}
h1{{font-size:34px;line-height:1.15;margin:0 0 4px;font-weight:600}}
.sub{{font-size:20px;color:#333;margin:0 0 10px}}
.by{{color:#555;font-size:14.5px;margin:0 0 18px}}
nav{{font-size:14.5px;margin:0 0 30px;padding:10px 0;border-top:1px solid #ddd;border-bottom:1px solid #ddd}}
nav a{{margin-right:18px}}
a{{color:#1a5fb4;text-decoration:none}} a:hover{{text-decoration:underline}}
h2{{font-size:23px;margin:46px 0 10px;padding-bottom:5px;border-bottom:2px solid #C89B5F;font-weight:600}}
h3{{font-size:18px;margin:30px 0 8px;font-weight:600}}
h4{{font-size:15px;margin:22px 0 6px;font-weight:600;color:#333}}
p{{margin:0 0 12px}}
ul{{margin:0 0 12px 22px;padding:0}} li{{margin-bottom:6px}}
.note{{color:#555;font-size:14.5px}}
table{{border-collapse:collapse;width:100%;margin:10px 0 18px;font:13.5px/1.4 -apple-system,"Helvetica Neue",Helvetica,Arial,sans-serif}}
th,td{{border-top:1px solid #e3e3e3;padding:7px 8px;text-align:left;vertical-align:top}}
thead th{{border-top:0;border-bottom:1px solid #bbb;color:#444;font-weight:600}}
tbody tr:last-child td{{border-bottom:1px solid #e3e3e3}}
td.cap{{min-width:200px;max-width:300px;color:#222}}
td.clip{{min-width:150px}}
audio{{display:block;width:100%;height:30px}}
.score,.lab{{color:#555;font-size:12px;margin-top:3px;white-space:nowrap}}
.lab{{margin:0 0 3px;font-weight:600}}
.wrap{{overflow-x:auto}}
figure{{margin:16px 0 22px}} figure img{{max-width:100%;height:auto;display:block}}
figcaption{{font:13.5px/1.45 -apple-system,"Helvetica Neue",Helvetica,Arial,sans-serif;color:#555;margin-top:6px}}
.rights{{background:#faf7f1;border-left:3px solid #C89B5F;padding:10px 14px;margin:14px 0}}
footer{{margin-top:56px;padding-top:12px;border-top:1px solid #ddd;color:#666;font-size:13px}}
code{{font-size:14px}}
</style>
</head>
<body>
<main>

<h1>QaraamiGen</h1>
<p class="sub">Adapting a text-to-music model to Somali qaraami from archival cassettes</p>
<p class="by">Khalid Ibrahim · Minneapolis, MN · {today} · <a href="mailto:{CONTACT}">{CONTACT}</a></p>

<nav><a href="#listen">Listen</a><a href="#results">Results</a><a href="#defect">The defect</a><a href="#method">Method</a><a href="#rights">Rights</a></nav>

<p>Somali <i>qaraami</i> is a modally organised, largely pentatonic song tradition, transmitted with
almost no notation and surviving mainly on aging cassette tape. This page asks whether a general
text-to-music model can learn something of that tradition from the tapes without the tapes leaving
their rights holders, and how one would know that it had. MusicGen, at three sizes, is adapted with
low-rank adapters on 43 hours of held archival audio, evaluated on songs it never saw, and heard
against its own base model on identical prompts and random seeds.</p>

<ul>
<li><b>Under a corrected training harness, every checkpoint of every run beats its base model on
held-out songs.</b> The correction matters: the Hugging Face MusicGen decoder applies dropout through
float attributes that module-level sweeps miss, and for two months that defect read as a negative
result.</li>
<li><b>The gain grows with scale.</b> Per-song test cross-entropy improves by {mg:.3f} nats on
MusicGen-medium and {lgn:.3f} on MusicGen-large, with bootstrap intervals over songs that clear zero.</li>
<li><b>The adapters put more trackable melody into the output</b>, up to twice the base model's at
the largest size, and learn the cassettes' tuning offset, at some cost in pentatonic conformity. Whether that trade sounds like qaraami is a
listening question, which is why the clips come first.</li>
</ul>

<div class="rights note">Everything audible on this page is model output. No source recording is
included, the training audio is not distributed, and the adapters are not released. Details under
<a href="#rights">Rights</a>.</div>

<h2 id="listen">Listen</h2>

<p>Each row is one prompt. The base model and the adapter receive the same text and the same random
seed; only the adapter weights differ. Under each clip: <b>PCS</b>, the duration-weighted fraction of
pitched frames within ±50 cents of the best-fitting anhemitonic-pentatonic set after a per-clip
tuning fit, and the <b>voiced fraction</b>, the share of frames with a trackable pitch. Read them
together; conformity of very little melody is not a win. Prompts are held-out test captions. The
catalogue-derived prompts carry performer credits from the Harvard finding aid; those are omitted
from the captions shown here.</p>

<h3>MusicGen-medium (1.5 B) and MusicGen-large (3.3 B), 15-second clips</h3>
<p class="note">Eight of the sixteen A/B prompts: the four synthetic qaraami prompts and the first four
catalogue prompts, fixed before listening. Both sizes were trained on the same {sc["total_clips"]:,}
clips and heard on the same prompts and seeds, so the columns are comparable across the row.</p>
<div class="wrap">{scale_table}</div>

<h3>MusicGen-small (0.6 B), one collection each, 10-second clips</h3>
<p class="note">The first two adapters, each trained on a single collection with rank-16 LoRA on the
decoder attention projections. First four pairs of each eight-pair listening set.</p>
{"".join(small_tables)}

<h3>Training progression, MusicGen-large</h3>
<p class="note">One held-out prompt sampled from the same seed at successive checkpoints:
<i>{esc(strip_credit(ctx["prog_caption"]))}</i>.</p>
<div class="wrap">{prog_table}</div>

<h3>Melody conditioning, preliminary</h3>
<p class="note">MusicGen-melody with no adapter, conditioned on the chroma of a held-out real qaraami
clip in place of a text-only prompt. This is the conditioning path a melody adapter would use; the
reference recordings are not included. The three clips with the most trackable melody of eight.</p>
<div class="wrap">{mel_table}</div>

<h2 id="results">Results</h2>

<h3>Scale runs</h3>
<p>Held-out per-song cross-entropy on {ln} unseen test songs ({el["test_clips"]} clips), base model
against adapter, with a bootstrap 95% interval resampled over songs rather than clips, because same-song
clips share a cassette and a channel and are not independent. PCS and voiced fraction are means over
the 16-clip A/B set.</p>
<div class="wrap">{scale_results}</div>
<p>The rigorous metric improves with size and the intervals do not overlap zero. The large adapter
reaches the lowest held-out cross-entropy in the programme. On the generation side the larger model
puts far more pitched, sung material into its output ({f3(el["ab"]["base"]["voiced_fraction_mean"])} →
{f3(el["ab"]["adapter"]["voiced_fraction_mean"])} voiced), and lands off the pentatonic set more often
while doing so ({f3(el["ab"]["base"]["pcs_mean"])} → {f3(el["ab"]["adapter"]["pcs_mean"])} PCS). At
sixteen prompts the PCS column is inside the scorer's noise; the voiced-fraction shift is not.</p>

<figure>
<img src="figures/ft7_scale_val_curves.png" alt="Validation cross-entropy per checkpoint for the medium and large runs">
<figcaption>Validation token cross-entropy at every checkpoint of the medium and large runs
(48 validation clips, song-level split). Both curves flatten by about step 2,500; the best held-out
per-song test cross-entropy is at step 2,750 for both.</figcaption>
</figure>

<h3>Small runs</h3>
<p>MusicGen-small, one collection per adapter, 15-second training clips. Validation and test are
song-level splits; test songs are unseen. Cross-entropy is not comparable across corpora.</p>
<div class="wrap">{small_results}</div>
<figure>
<img src="figures/ft3_pcs_voiced.png" alt="PCS and voiced fraction for base, adapter and real clips on both corpora">
<figcaption>Pentatonic conformity and voiced fraction for base model, adapter and real held-out clips,
eight prompts per generated group. The adapters produce more melody than the base model and, on both
corpora, more than the real clips; conformity is similar (oud) or lower (Harvard). They also learn the
cassettes' tuning offset: base output sits near A440, adapter output about 25 cents off, as the tapes are.</figcaption>
</figure>

<h3>What is not claimed</h3>
<ul>
<li>No listening study yet. The A/B sets exist so that one can be run; the numbers above do not
substitute for it.</li>
<li>No long-form structure: 10 to 15 second clips.</li>
<li>Not a model of Somali music at large. Each adapter is a model of the collections it saw.</li>
<li>Small-model margins are small (0.5 to 3%), real and reproducible, and stated without significance
tests; the scale runs are where the intervals are reported.</li>
</ul>

<h2 id="defect">The defect that looked like a negative result</h2>

<p>The first two months of fine-tuning produced a clean negative: at two learning rates and on two
corpora, held-out loss rose from 4.6 to about 6.7 nats within 250 steps and never recovered, while
the generations lost half their melodic content. It was written up as such. It was the harness.</p>

<figure>
<img src="figures/ft2_dropout_probe.png" alt="Train-mode versus eval-mode loss on identical weights">
<figcaption>A five-condition probe on identical zero-initialised LoRA weights. Eval-mode loss is 4.05
nats; train-mode loss is 9.74, worse than uniform random over the 2,048-token codebook (7.62). Zeroing
every <code>nn.Dropout</code> module (C), disabling checkpointing (D), or putting the encoders in eval
mode (E) changes nothing.</figcaption>
</figure>

<p>The Hugging Face MusicGen decoder applies dropout <i>functionally</i>, through 37 float attributes
consumed by <code>F.dropout(…, training=self.training)</code>, which a sweep over
<code>nn.Dropout</code> modules never touches. Optimisation was fitting a forward path that evaluation
never saw. Zeroing those attributes makes the train and eval paths identical; the first corrected run
beat the base model at every checkpoint, and the Harvard corpus, which had been the "structural
negative", did the same. On the medium and large decoders the same fix zeroes 61 attributes. The
failure mode is generic to this model family, which is why it is reported here rather than
buried.</p>

<figure>
<img src="figures/ft1_val_curves.png" alt="Validation curves under the broken and the fixed harness">
<figcaption>Validation cross-entropy for every MusicGen-small run. Dashed: the broken harness, both
corpora, all learning rates. Solid: the corrected harness. Dotted: the base model.</figcaption>
</figure>

<h2 id="method">Method</h2>

<h3>Data</h3>
<p>Three held collections of Somali qaraami, 43.1 hours in all, none cleared for public release:
the Maryan "Aryette" Omar Ali Collection at Harvard's Archive of World Music (22.6 h, mid-century
ensemble song on cassette), a privately shared oud-led collection (5.4 h, 28 songs, performers
unlisted), and 15.1 h of qaraami recordings recovered from the project's own session archives. For the
scale runs the audio was cut into 30-second clips at 32 kHz mono, split by song so that no song appears
in two splits: {sc["clips"]["train"]:,} training clips from {sc["songs"]["train"]} songs,
{sc["clips"]["val"]:,} validation from {sc["songs"]["val"]}, {sc["clips"]["test"]:,} test from
{sc["songs"]["test"]}. Captions are measured rather than written: tempo from the audio, tonic from the
pentatonic fit, instrumentation and era from the catalogue.</p>

<h3>Models and training</h3>
<div class="wrap"><table>
<thead><tr><th></th><th>MusicGen-small</th><th>MusicGen-medium</th><th>MusicGen-large</th></tr></thead>
<tbody>
<tr><td>parameters</td><td>{PARAMS["small"]}</td><td>{PARAMS["medium"]}</td><td>{PARAMS["large"]}</td></tr>
<tr><td>LoRA</td><td>r 16, α 32, attention q/k/v/out</td><td>r {m["cfg"]["rank"]}, α {m["cfg"]["alpha"]}, attention + FFN (q/k/v/out, fc1, fc2)</td><td>r {cfg["rank"]}, α {cfg["alpha"]}, attention + FFN</td></tr>
<tr><td>trainable</td><td>6.3 M</td><td>{TRAINABLE["medium"]}</td><td>{TRAINABLE["large"]}</td></tr>
<tr><td>clips</td><td>15 s, one collection</td><td>30 s, all three</td><td>30 s, all three</td></tr>
<tr><td>schedule</td><td>lr 1e-4 cosine, 1,000 to 3,000 steps</td><td>lr {m["cfg"]["lr"]:g} cosine, {m["cfg"]["total_steps"]:,} steps, {m["cfg"]["warmup"]} warm-up</td><td>lr {cfg["lr"]:g} cosine, {cfg["total_steps"]:,} steps, {cfg["warmup"]} warm-up</td></tr>
<tr><td>batch</td><td>1 × 4 accumulation</td><td>1 × {m["cfg"]["grad_accum"]}</td><td>1 × {cfg["grad_accum"]}</td></tr>
<tr><td>compute</td><td>Apple M1 / M5 Max, fp32 on MPS</td><td>M5 Max, {STEP_RATE["medium"]}/step, {PEAK_MEM["medium"]} peak</td><td>M5 Max, {STEP_RATE["large"]}/step, {PEAK_MEM["large"]} peak</td></tr>
<tr><td>dropout attributes zeroed</td><td>37</td><td>61</td><td>61</td></tr>
</tbody></table></div>
<p>Everything runs on a single laptop, fp32 on Apple silicon, with precomputed EnCodec tokens and
delay-pattern labels. Base weights are unchanged; the adapters are hot-swapped at inference by a
local service that labels every generation with the adapter's corpus and a non-distribution line.</p>

<h3>Evaluation</h3>
<p>Two families of measurement. <b>Likelihood</b>: token cross-entropy on unseen songs, averaged within
song and then across songs, with the confidence interval bootstrapped over songs. The song is the
independent unit on archival audio; an embedding audit on this corpus found that nearest neighbours
retrieve same-cassette material at thirteen times chance, so clip-level splits leak the channel.
<b>Output</b>: PCS and voiced fraction from a CREPE pitch track on generated audio, the same scorer the
project uses to measure intonation in the real recordings, plus paired A/B sets for listening. PCS is
reported only beside the voiced fraction, and treated as a direction rather than a statistic at these
sample sizes.</p>

<h2 id="rights">Rights and provenance</h2>
<p>The Harvard collection is not rights-cleared for redistribution and written permission from the
Loeb Music Library is outstanding; the oud collection's rights remain with its performers, who are not
named; the third source is of mixed and partly unknown provenance. All three are used for training and
measurement only. No recording from any of them is included on this page, in the repository, or in any
public artifact, and the adapters, which are derived from them, are not distributed. The clips here are
the outputs of models conditioned on text, generated for evaluation, and are labelled as such wherever
they appear. Data provenance, per-collection status and the outstanding items are documented in the
repository.</p>

<footer>
Generated from the run artifacts by <code>apps/ai-service/scripts/build_demo_page.py</code>
at commit {esc(ctx["commit"])} on {dt.date.today().isoformat()}. Code, model cards, evaluation report
and the paper draft are available on request.
</footer>

</main>
</body>
</html>
"""


def inline_assets(page: str) -> str:
    def data_uri(rel: str) -> str:
        p = OUT / rel
        mime = "audio/mpeg" if p.suffix == ".mp3" else "image/png"
        return f"data:{mime};base64,{base64.b64encode(p.read_bytes()).decode('ascii')}"
    return re.sub(r'src="((?:audio|figures)/[^"]+)"', lambda mm: f'src="{data_uri(mm.group(1))}"', page)


# -------------------------------------------------------------------- main

def main() -> None:
    scale = {tag: load_scale(tag) for tag in ("medium", "large")}
    scale_captions = read_captions(DATA / "ab_large")
    best_step = int(scale["large"]["eval"]["best_ckpt"].split("_")[-1])
    prog_steps = PROGRESSION_STEPS + [best_step]

    clips: dict[str, Clip] = {}
    for tag in ("medium", "large"):
        pairs = {p["pair"]: p for p in scale[tag]["eval"]["ab"]["pairs"]}
        for i in SCALE_PAIRS:
            for side in ("base", "adapter"):
                sc = pairs[i][side]
                clips[f"{tag}_{i:03d}_{side}"] = Clip(
                    DATA / f"ab_{tag}" / f"pair{i:03d}_{side}.wav", f"{tag}_{i:03d}_{side}",
                    sc.get("pcs") if sc.get("scored") else None,
                    sc.get("voiced_fraction") if sc.get("scored") else None)
    small_captions, small_summary = {}, {}
    for key, info in SMALL.items():
        d = DATA / info["set"]
        small_captions[key] = read_captions(d)
        rows = {side: pcs_csv(name) for side, name in zip(("base", "adapter"), info["csv"])}
        for i in SMALL_PAIRS:
            for side, fname in (("base", "base"), ("adapter", "finetuned")):
                r = rows[side].get(i, {})
                clips[f"{key}_{i:03d}_{side}"] = Clip(
                    d / f"pair{i:03d}_{fname}.wav", f"{key}_{i:03d}_{side}",
                    num(r.get("pcs")), num(r.get("voiced_fraction")))
        summ = {}
        for side, name in zip(("base", "adapter"), info["csv"]):
            g = json.loads((DATA / "eval_pcs" / f"{name}.json").read_text())
            summ[f"pcs_{side}"] = g["pcs_mean"]
            summ[f"voiced_{side}"] = g["voiced_fraction_mean"]
        small_summary[key] = summ
    for s in prog_steps:
        clips[f"large_step{s:04d}"] = Clip(RUNS / "qaraami_large_r32/samples" / f"step_{s:04d}.wav", f"large_step{s:04d}")
    mel = json.loads((DATA / "ab_melody/melody_condition.json").read_text())
    melody_clips = []
    for c in sorted(mel["clips"], key=lambda c: -c["voiced_fraction"])[:N_MELODY]:
        clip = Clip(DATA / "ab_melody" / c["file"], f"melody_{c['i']:03d}", c["pcs"], c["voiced_fraction"])
        clips[clip.name] = clip
        melody_clips.append(clip)

    missing = [c.src for c in clips.values() if not c.src.exists()]
    if missing:
        sys.exit("missing source clips:\n  " + "\n  ".join(map(str, missing)))

    OUT.mkdir(parents=True, exist_ok=True)
    transcode(list(clips.values()))
    figure_scale_val({tag: scale[tag]["val_curve"] for tag in scale})
    FIGOUT.mkdir(exist_ok=True)
    for name in ("ft1_val_curves", "ft2_dropout_probe", "ft3_pcs_voiced", "ft7_scale_val_curves"):
        shutil.copy2(FIG / f"{name}.png", FIGOUT / f"{name}.png")

    commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=REPO, capture_output=True, text=True).stdout.strip() or "unknown"
    ctx = {
        "scale": scale, "scale_captions": scale_captions, "clips": clips, "best_step": best_step,
        "prog_steps": prog_steps, "prog_caption": (RUNS / "qaraami_large_r32/sample_caption.txt").read_text().strip(),
        "melody_clips": melody_clips, "small_captions": small_captions, "small_summary": small_summary,
        "splits": split_counts(), "commit": commit,
    }
    page = build_html(ctx)
    (OUT / "index.html").write_text(page, encoding="utf-8")
    bundle = OUT / "QaraamiGen-demo.html"
    bundle.write_text(inline_assets(page), encoding="utf-8")

    n_audio = len(clips)
    mb = sum((AUDIO / f"{c.name}.mp3").stat().st_size for c in clips.values()) / 1e6
    print(f"{n_audio} clips, {mb:.1f} MB of audio -> {OUT.relative_to(REPO)}/index.html")
    print(f"single file: {bundle.relative_to(REPO)} ({bundle.stat().st_size / 1e6:.1f} MB)")


if __name__ == "__main__":
    main()
