"""Build the shareable QaraamiGen demo page from the run artifacts on disk.

A plain academic page in the style of a research group's demo index: prose,
tables, figures and inline audio players, base model against adapter on the
same prompt and seed. Every number comes from the eval JSON, run configs and
scorer CSVs; every clip is model output already generated by the evaluation
scripts. Nothing is generated or scored here, so the page cannot disagree with
the reports.

Outputs (docs/demo/site/):
  index.html            relative links into audio/ and figures/  (tracked)
  audio/*.mp3           transcoded from the A/B wavs, 96 kb/s mono  (ignored)
  figures/*.png         copied from docs/figures                    (ignored)
  QaraamiGen-demo.html  single self-contained file, audio and figures
                        inlined as data URIs; the thing to send      (ignored)

Also writes docs/figures/ft7_scale_val_curves.{png,svg} (validation CE per
checkpoint for the medium and large runs, from runs/qaraami_*_r32/loss.csv).

Clip selection is fixed by rule, not by ear: the four synthetic qaraami prompts
and the first four catalogue prompts of the 16-prompt scale A/B set; the first
four pairs of each small-model set; the three melody-conditioned clips with the
highest voiced fraction; the large run's per-checkpoint sample at steps 250,
1000, 2000 and the best checkpoint. Catalogue prompts carry performer credits
from the Harvard finding aid; those are omitted from the displayed captions.

Blind listening results, if any exist in data/listening/ (written by
ab_listen.py's paired-comparison test), are summarised in the Results section;
until then the page says the study is pending.

Usage (from the repo root, the musicgen env has matplotlib):
  ~/ai/musicgen-env/bin/python apps/ai-service/scripts/build_demo_page.py
"""
from __future__ import annotations

import base64
import csv
import datetime as dt
import html
import json
import math
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
DATA = REPO / "data"
RUNS = REPO / "runs"
FIG = REPO / "docs/figures"
OUT = REPO / "docs/demo/site"
AUDIO = OUT / "audio"
FIGOUT = OUT / "figures"
LISTENING = DATA / "listening"

SCALE_PAIRS = [0, 1, 2, 3, 4, 8, 10, 11]
SMALL_PAIRS = [0, 1, 2, 3]
PROGRESSION_STEPS = [250, 1000, 2000]  # plus the best checkpoint, read from eval
N_MELODY = 3
MP3_KBPS = 96
CONTACT = "research@somalimusicarchive.com"

# MusicGen-small results, docs/eval/EVALUATION.md T1 and T4 (generated by eval_report.py).
SMALL = {
    "oud": {
        "title": "oud adapter",
        "corpus": "private oud (kaban) qaraami collection, 28 songs",
        "val": (4.5132, 4.4785), "test": (2.6302, 2.6092), "best": "step 500 of 1,000",
        "set": "oud_ab_listening", "csv": ("oud_base", "oud_lora500"),
        "real": {"pcs": 0.914, "voiced": 0.435},
    },
    "harvard_raw": {
        "title": "harvard_raw adapter",
        "corpus": "Maryan “Aryette” Omar Ali Collection, Harvard AWM Spec Coll 103, 119 tracks",
        "val": (4.6262, 4.5501), "test": (4.8363, 4.7468), "best": "step 2,750 of 3,000",
        "set": "harvard_ab_listening", "csv": ("harvard_base", "harvard_lora1500"),
        "real": {"pcs": 0.847, "voiced": 0.530},
    },
}
PARAMS = {"small": "0.59 B", "medium": "1.5 B", "large": "3.3 B"}
TRAINABLE = {"medium": "61.3 M", "large": "81.8 M"}
STEP_RATE = {"medium": "~10 s", "large": "~16 s"}
PEAK_MEM = {"medium": "11.3 GB", "large": "16.3 GB"}
SET_LABEL = {"ab_large": "MusicGen-large", "ab_medium": "MusicGen-medium",
             "oud_ab_listening": "small, oud adapter", "harvard_ab_listening": "small, harvard_raw adapter"}


@dataclass
class Clip:
    src: Path
    name: str            # output basename without extension
    pcs: float | None = None
    voiced: float | None = None

    @property
    def rel(self) -> str:
        return f"audio/{self.name}.mp3"


# ------------------------------------------------------------------ inputs

def strip_credit(caption: str) -> str:
    return re.sub(r",\s*performed by .*$", "", caption).strip()


def read_captions(d: Path) -> dict[int, str]:
    out: dict[int, str] = {}
    for line in (d / "CAPTIONS.txt").read_text().splitlines():
        m = re.match(r"pair(\d{3}):\s*(.*)", line)
        if m:
            out[int(m.group(1))] = m.group(2).strip()
    return out


def pcs_csv(name: str) -> dict[int, dict]:
    out: dict[int, dict] = {}
    with (DATA / "eval_pcs" / f"{name}.csv").open() as fh:
        for row in csv.DictReader(fh):
            m = re.search(r"(?:pair|gen_)(\d{3})", row.get("clip", ""))
            if m:
                out[int(m.group(1))] = row
    return out


def num(x) -> float | None:
    try:
        return float(x)
    except (TypeError, ValueError):
        return None


def load_scale(tag: str) -> dict:
    e = json.loads((RUNS / f"qaraami_{tag}_r32" / f"eval_{tag}.json").read_text())
    cfg = json.loads((RUNS / f"qaraami_{tag}_r32" / "config.json").read_text())
    steps, vals = [], []
    with (RUNS / f"qaraami_{tag}_r32" / "loss.csv").open() as fh:
        for row in csv.DictReader(fh):
            if row["val_loss"]:
                steps.append(int(row["step"]))
                vals.append(float(row["val_loss"]))
    return {"eval": e, "cfg": cfg, "val_curve": (steps, vals)}


def split_counts() -> dict:
    clips: dict[str, int] = {}
    songs: dict[str, set] = {}
    for line in (DATA / "scale_captions.jsonl").open():
        d = json.loads(line)
        clips[d["split"]] = clips.get(d["split"], 0) + 1
        songs.setdefault(d["split"], set()).add(d["song_sha256"])
    all_songs = set().union(*songs.values())
    return {"clips": clips, "songs": {k: len(v) for k, v in songs.items()},
            "total_clips": sum(clips.values()), "total_songs": len(all_songs)}


def wilson(k: int, n: int, z: float = 1.96) -> tuple[float, float]:
    if n == 0:
        return (0.0, 0.0)
    p = k / n
    d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return (c - h, c + h)


def listening_results() -> dict[str, dict]:
    """Latest blind paired-comparison result per set, from data/listening/*.json."""
    out: dict[str, dict] = {}
    if not LISTENING.is_dir():
        return out
    for p in sorted(LISTENING.glob("*.json")):
        r = json.loads(p.read_text())
        s = r.get("summary") or {}
        if r.get("set") and s.get("n"):
            out[r["set"]] = {"file": p.name, "listener": r.get("listener", ""), "date": r.get("date", ""),
                             "n": s["n"], "adapter": s["adapter"], "base": s["base"], "none": s["none"]}
    return out


# ---------------------------------------------------------------- transcode

def transcode(clips: list[Clip]) -> None:
    AUDIO.mkdir(parents=True, exist_ok=True)
    for c in clips:
        dst = AUDIO / f"{c.name}.mp3"
        if dst.exists() and dst.stat().st_mtime >= c.src.stat().st_mtime:
            continue
        subprocess.run(
            ["ffmpeg", "-v", "error", "-y", "-i", str(c.src), "-ac", "1", "-ar", "32000",
             "-codec:a", "libmp3lame", "-b:a", f"{MP3_KBPS}k", "-id3v2_version", "0", str(dst)],
            check=True)


# ------------------------------------------------------------------ figure

def figure_scale_val(curves: dict[str, tuple[list[int], list[float]]]) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    plt.rcParams.update({"figure.dpi": 150, "font.size": 9, "axes.spines.top": False,
                         "axes.spines.right": False, "font.family": "sans-serif"})
    colors = {"medium": "#2f6fb0", "large": "#c8843a"}   # validated pair, light surface
    fig, ax = plt.subplots(figsize=(7.4, 3.6))
    xmax = max(s[-1] for s, _ in curves.values())
    for tag, (steps, vals) in curves.items():
        ax.hlines(vals[0], -60, xmax, color=colors[tag], lw=1, ls=(0, (1, 3)), alpha=0.8)
        ax.plot(steps, vals, color=colors[tag], lw=2, marker="o", ms=4,
                solid_joinstyle="round", solid_capstyle="round", label=f"MusicGen-{tag}, LoRA r32")
        ax.text(xmax + 60, vals[0], f"base {vals[0]:.4f}", va="center", fontsize=7.5, color="#666")
        ax.text(xmax + 60, vals[-1], f"{vals[-1]:.4f}", va="center", fontsize=8, color="#222")
    ax.set_xlim(-60, xmax + 520)
    ax.set_xlabel("optimizer step")
    ax.set_ylabel("validation token cross-entropy (nats)")
    ax.set_title("Validation cross-entropy per checkpoint; dotted lines are each model's base", fontsize=9)
    ax.grid(axis="y", color="#e6e6e6", lw=0.8)
    ax.set_axisbelow(True)
    ax.legend(frameon=False, fontsize=8, loc="center right")
    fig.tight_layout()
    fig.savefig(FIG / "ft7_scale_val_curves.png")
    fig.savefig(FIG / "ft7_scale_val_curves.svg")
    plt.close(fig)


# ------------------------------------------------------------------- html

def esc(s: object) -> str:
    return html.escape(str(s))


def f3(x: float | None) -> str:
    return "–" if x is None else f"{x:.3f}"


def f4(x: float) -> str:
    return f"{x:.4f}"


def player(c: Clip | None, scored: bool = True) -> str:
    if c is None:
        return "<td>–</td>"
    s = ""
    if scored:
        if c.pcs is not None or c.voiced is not None:
            s = f'<div class="score">PCS {f3(c.pcs)} · voiced {f3(c.voiced)}</div>'
        else:
            s = '<div class="score">too little pitched content to score</div>'
    return f'<td class="clip"><audio controls preload="metadata" src="{esc(c.rel)}"></audio>{s}</td>'


def delta(a: float, b: float) -> str:
    return f"{b - a:+.3f}"


def listening_html(res: dict[str, dict]) -> str:
    if not res:
        return ""
    rows = []
    for name in ("ab_large", "ab_medium", "oud_ab_listening", "harvard_ab_listening"):
        r = res.get(name)
        if not r:
            continue
        lo, hi = wilson(r["adapter"], r["n"])
        rows.append(f'<tr><td>{esc(SET_LABEL.get(name, name))}</td><td>{r["n"]}</td>'
                    f'<td><b>{r["adapter"]}</b></td><td>{r["base"]}</td><td>{r["none"]}</td>'
                    f'<td>{r["adapter"] / r["n"]:.2f} [{lo:.2f}, {hi:.2f}]</td><td>{esc(r["date"][:10])}</td></tr>')
    return (
        '<h3>2.3 Blind paired comparison</h3>'
        '<p>For each pair the two clips were presented as A and B in an order randomised per pair, without '
        'scores or file names, and I chose the one that sounded more like qaraami to me, or neither. I am the '
        'only listener so far and I know the project, but not which clip was which. The interval is a 95% '
        'Wilson interval on the adapter preference rate, counting every pair.</p>'
        '<div class="wrap"><table><thead><tr><th>set</th><th>pairs</th><th>adapter preferred</th>'
        '<th>base preferred</th><th>no preference</th><th>adapter rate [95% CI]</th><th>date</th></tr></thead>'
        f'<tbody>{"".join(rows)}</tbody></table></div>')


DPO_STAGES = (("small_oud", "MusicGen-small, oud adapter"), ("medium_v1", "MusicGen-medium, first recipe"),
              ("large", "MusicGen-large"), ("medium", "MusicGen-medium"))
N_DPO_PAIRS = 6


def dpo_ok(e: dict) -> bool:
    """A round passes the guards when it moved toward the real oud clips and the held-out CE rose by less than 0.5 nats."""
    ce = e["held_out_oud_token_ce"]
    return e["after"]["oud_dist"] < e["before"]["oud_dist"] and (ce["after"] - ce["before"]) < 0.5


def dpo_results() -> list[dict]:
    """One entry per finished preference round: config, eval summary, A/B scores."""
    out = []
    for tag, label in DPO_STAGES:
        run = RUNS / f"dpo_{tag}"
        ev = run / "eval_round_1.json"
        if not ev.exists():
            continue
        e = json.loads(ev.read_text())
        cfg = json.loads((run / "config.json").read_text())
        ab = DATA / f"ab_dpo_{tag}"
        scores = json.loads((ab / "ab_scores.json").read_text()) if (ab / "ab_scores.json").exists() else {"pairs": []}
        out.append({"tag": tag, "label": label, "eval": e, "cfg": cfg, "ab_dir": ab, "scores": scores})
    return out


def dpo_html(stages: list[dict], clips: dict[str, Clip], listening: dict[str, dict]) -> str:
    if not stages:
        return ""
    rows = []
    for s in stages:
        e, b, a = s["eval"], s["eval"]["before"], s["eval"]["after"]
        ce = e["held_out_oud_token_ce"]
        snr = f'{f3(b.get("band_snr_db"))} → {f3(a.get("band_snr_db"))}' if b.get("band_snr_db") is not None else "–"
        sp = e.get("spread_pca") or {}
        spread = f'{f3(sp.get("before"))} → {f3(sp.get("after"))}' if sp else "–"
        rows.append(f'<tr><td>{esc(s["label"])}{"" if dpo_ok(e) else " (failed the guards)"}</td><td>{e["pairs"]}</td><td>{e["steps"]}</td>'
                    f'<td>{f3(b["oud_dist"])} → <b>{f3(a["oud_dist"])}</b></td><td>{snr}</td>'
                    f'<td>{f3(b["pcs"])} → {f3(a["pcs"])}</td><td>{f3(b["voiced_fraction"])} → {f3(a["voiced_fraction"])}</td>'
                    f'<td>{f4(ce["before"])} → {f4(ce["after"])}</td><td>{spread}</td></tr>')
    real_spread = next((s["eval"]["spread_pca"]["real_oud_test"] for s in stages if s["eval"].get("spread_pca")), None)
    table = ('<table><thead><tr><th>model</th><th>pairs</th><th>steps</th><th>distance to real oud, before → after</th>'
             '<th>band SNR dB, before → after</th><th>PCS</th><th>voiced fraction</th><th>held-out oud token CE</th>'
             f'<th>spread{" (real clips " + f3(real_spread) + ")" if real_spread else ""}</th></tr></thead>'
             f'<tbody>{"".join(rows)}</tbody></table>')
    passing = [s for s in stages if dpo_ok(s["eval"])]
    top = (passing or stages)[-1]
    prow = []
    for row in top["scores"]["pairs"][:N_DPO_PAIRS]:
        i = row["pair"]
        cb, ca = clips.get(f'dpo_{top["tag"]}_{i:03d}_base'), clips.get(f'dpo_{top["tag"]}_{i:03d}_adapter')
        if cb and ca:
            prow.append(f'<tr><td class="cap">{esc(row["caption"])}</td>{player(cb)}{player(ca)}</tr>')
    pairs_table = ('<table class="ab"><thead><tr><th>prompt</th><th>before</th><th>after</th></tr></thead>'
                   f'<tbody>{"".join(prow)}</tbody></table>') if prow else ""
    blind = []
    for s in stages:
        r = listening.get(f'ab_dpo_{s["tag"]}')
        if r:
            lo, hi = wilson(r["adapter"], r["n"])
            blind.append(f'{esc(s["label"])}: after preferred in {r["adapter"]} of {r["n"]} pairs, before in {r["base"]}, '
                         f'neither in {r["none"]} (rate {r["adapter"] / r["n"]:.2f}, 95% interval {lo:.2f} to {hi:.2f})')
    blind_html = ('<p>Blind paired comparison, same protocol as 2.3: ' + "; ".join(blind) + '.</p>') if blind else \
        '<p>The before-versus-after blind test on these sets has not been run yet.</p>'
    return f"""
<h2 id="dpo">5. Preference optimisation</h2>

<p>The supervised adapters learn the corpus as recorded, and the blind test said so: the large adapter was
preferred and called noisy in the same breath. As a next step I optimised the adapters for what I want to
hear rather than for the likelihood of the tapes, using direct preference optimisation on the adapter
weights with a reward measured on the model's own samples. The reward has three terms: Mahalanobis
distance to the real oud recordings in the embedding space of MERT-v1-95M (fitted on 1,512 real clips),
a hiss measure from the spread of energy in the 3 to 10 kHz band (real cassettes 4.5 dB, real oud
recordings 8.3, base MusicGen 10.4), and the pentatonic-melody score, combined as a z-scored sum with a
penalty for near-silence. Each round draws four samples per prompt from the adapter on held prompts from
the oud caption grammar, keeps the best and the worst as a preference pair, and trains the adapter
against the round's starting weights as the reference, with length-normalised token log-probabilities
and every dropout disabled so that policy and reference are the same function of the weights.</p>

<div class="wrap">{table}</div>

<p>The trade is explicit. Distance to the real recordings falls to the level of the real clips themselves
(4.1 to 4.2 on this scale), and held-out token cross-entropy on unseen oud songs rises by an amount that
depends on how far the policy is allowed to move; the first medium round, without a likelihood anchor or
a KL budget, drifted into louder, band-limited output and is kept in the table as a failure. The spread
column is the mean pairwise distance between the generated clips in the same space: every round narrows
the output distribution, the large round least, and all of them sit below the spread of the real
recordings. Whether the narrower, closer output sounds better is a listening question. The pairs below
are the same prompt and seed before and after the optimisation of {esc(top["label"])}.</p>

<div class="wrap">{pairs_table}</div>

{blind_html}
"""


def build_html(ctx: dict) -> str:
    m, lg = ctx["scale"]["medium"], ctx["scale"]["large"]
    em, el = m["eval"], lg["eval"]
    sc = ctx["splits"]
    today = dt.date.today()
    listening = ctx["listening"]

    def ce(e):
        c = e["per_song_ce"]
        i = c["improvement_base_minus_adapter"]
        return c["base"]["mean"], c["adapter"]["mean"], i["mean"], i["ci95"], c["n_songs"]

    # ---- audio: scale table
    rows = []
    for i in SCALE_PAIRS:
        cap = strip_credit(ctx["scale_captions"][i])
        cells = "".join(player(ctx["clips"][f"{tag}_{i:03d}_{side}"])
                        for tag in ("medium", "large") for side in ("base", "adapter"))
        rows.append(f'<tr><td class="cap">{esc(cap)}</td>{cells}</tr>')
    scale_table = (
        '<table class="ab"><thead><tr><th>prompt (held-out test caption)</th>'
        '<th>medium, base</th><th>medium, adapter</th><th>large, base</th><th>large, adapter</th></tr></thead>'
        f'<tbody>{"".join(rows)}</tbody></table>')

    # ---- audio: small tables
    small_tables = []
    for key, info in SMALL.items():
        caps = ctx["small_captions"][key]
        rows = []
        for i in SMALL_PAIRS:
            rows.append(f'<tr><td class="cap">{esc(strip_credit(caps[i]))}</td>'
                        f'{player(ctx["clips"][f"{key}_{i:03d}_base"])}{player(ctx["clips"][f"{key}_{i:03d}_adapter"])}</tr>')
        small_tables.append(
            f'<h4>{esc(info["title"])}: {esc(info["corpus"])}</h4>'
            '<table class="ab"><thead><tr><th>prompt</th><th>base</th><th>adapter</th></tr></thead>'
            f'<tbody>{"".join(rows)}</tbody></table>')

    # ---- audio: progression
    prog_cells = "".join(
        f'<td class="clip"><div class="lab">step {s:,}{" (best)" if s == ctx["best_step"] else ""}</div>'
        f'<audio controls preload="metadata" src="{esc(ctx["clips"][f"large_step{s:04d}"].rel)}"></audio></td>'
        for s in ctx["prog_steps"])
    prog_table = f'<table class="ab"><tbody><tr>{prog_cells}</tr></tbody></table>'

    # ---- audio: melody
    mel_cells = "".join(player(c) for c in ctx["melody_clips"])
    mel_table = f'<table class="ab"><tbody><tr>{mel_cells}</tr></tbody></table>'

    # ---- results tables
    def scale_row(tag, d):
        e = d["eval"]
        b, a, g, ci, n = ce(e)
        ab = e["ab"]
        return (f'<tr><td>MusicGen-{tag}</td><td>{PARAMS[tag]}</td><td>{TRAINABLE[tag]}</td>'
                f'<td>{esc(e["best_ckpt"].replace("ckpt_step_", "step "))}</td>'
                f'<td>{f4(b)} → <b>{f4(a)}</b></td><td>+{g:.3f} [{ci[0]:.3f}, {ci[1]:.3f}]</td>'
                f'<td>{f3(ab["base"]["pcs_mean"])} → {f3(ab["adapter"]["pcs_mean"])} ({delta(ab["base"]["pcs_mean"], ab["adapter"]["pcs_mean"])})</td>'
                f'<td>{f3(ab["base"]["voiced_fraction_mean"])} → {f3(ab["adapter"]["voiced_fraction_mean"])} ({delta(ab["base"]["voiced_fraction_mean"], ab["adapter"]["voiced_fraction_mean"])})</td></tr>')

    scale_results = (
        '<table><thead><tr><th>model</th><th>params</th><th>LoRA params</th><th>best ckpt</th>'
        '<th>per-song test CE, base → adapter</th><th>gain (nats), 95% CI</th>'
        '<th>PCS, base → adapter</th><th>voiced fraction, base → adapter</th></tr></thead>'
        f'<tbody>{scale_row("medium", m)}{scale_row("large", lg)}</tbody></table>')

    def small_row(key, info):
        s = ctx["small_summary"][key]
        return (f'<tr><td>{esc(info["title"])}</td><td>{esc(info["corpus"])}</td><td>{esc(info["best"])}</td>'
                f'<td>{f4(info["val"][0])} → <b>{f4(info["val"][1])}</b></td>'
                f'<td>{f4(info["test"][0])} → <b>{f4(info["test"][1])}</b></td>'
                f'<td>{f3(s["pcs_base"])} → {f3(s["pcs_adapter"])} (real clips {f3(info["real"]["pcs"])})</td>'
                f'<td>{f3(s["voiced_base"])} → {f3(s["voiced_adapter"])} (real clips {f3(info["real"]["voiced"])})</td></tr>')

    small_results = (
        '<table><thead><tr><th>adapter</th><th>corpus</th><th>best ckpt</th><th>val CE</th>'
        '<th>test CE (unseen songs)</th><th>PCS, base → adapter</th><th>voiced fraction, base → adapter</th></tr></thead>'
        f'<tbody>{"".join(small_row(k, v) for k, v in SMALL.items())}</tbody></table>')

    mb, ma, mg, mci, mn = ce(em)
    lb, la, lgn, lci, ln = ce(el)
    cfg = lg["cfg"]
    vb, va = el["ab"]["base"]["voiced_fraction_mean"], el["ab"]["adapter"]["voiced_fraction_mean"]
    pb, pa = el["ab"]["base"]["pcs_mean"], el["ab"]["adapter"]["pcs_mean"]

    if listening:
        listening_limit = ("The listening results in 2.3 come from one listener, me. A study with Somali "
                           "musicians as listeners is the next step and has not been done.")
    else:
        listening_limit = ("I have not yet run a listening study. The paired A/B sets were generated for one, "
                           "and the blind paired-comparison protocol is in the repository.")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>QaraamiGen: adapting a text-to-music model to Somali qaraami</title>
<style>
body{{margin:0;background:#fff;color:#1b1b1b;font:16px/1.55 Charter,"Iowan Old Style","Palatino Linotype",Georgia,serif}}
main{{max-width:940px;margin:0 auto;padding:44px 28px 80px}}
h1{{font-size:32px;line-height:1.15;margin:0 0 4px;font-weight:600}}
.sub{{font-size:19px;color:#333;margin:0 0 10px}}
.by{{color:#555;font-size:14.5px;margin:0 0 18px}}
nav{{font-size:14.5px;margin:0 0 30px;padding:10px 0;border-top:1px solid #ddd;border-bottom:1px solid #ddd}}
nav a{{margin-right:18px}}
a{{color:#1a5fb4;text-decoration:none}} a:hover{{text-decoration:underline}}
h2{{font-size:22px;margin:46px 0 10px;padding-bottom:5px;border-bottom:1px solid #bbb;font-weight:600}}
h3{{font-size:17.5px;margin:30px 0 8px;font-weight:600}}
h4{{font-size:15px;margin:22px 0 6px;font-weight:600;color:#333}}
p{{margin:0 0 12px}}
ul{{margin:0 0 12px 22px;padding:0}} li{{margin-bottom:6px}}
.note{{color:#555;font-size:14.5px}}
table{{border-collapse:collapse;width:100%;margin:10px 0 18px;font:13.5px/1.4 -apple-system,"Helvetica Neue",Helvetica,Arial,sans-serif}}
th,td{{border-top:1px solid #e3e3e3;padding:7px 8px;text-align:left;vertical-align:top}}
thead th{{border-top:0;border-bottom:1px solid #bbb;color:#444;font-weight:600}}
tbody tr:last-child td{{border-bottom:1px solid #e3e3e3}}
td.cap{{min-width:200px;max-width:300px;color:#222}}
td.clip{{min-width:150px}}
audio{{display:block;width:100%;height:30px}}
.score,.lab{{color:#555;font-size:12px;margin-top:3px;white-space:nowrap}}
.lab{{margin:0 0 3px;font-weight:600}}
.wrap{{overflow-x:auto}}
figure{{margin:16px 0 22px}} figure img{{max-width:100%;height:auto;display:block}}
figcaption{{font:13.5px/1.45 -apple-system,"Helvetica Neue",Helvetica,Arial,sans-serif;color:#555;margin-top:6px}}
footer{{margin-top:56px;padding-top:12px;border-top:1px solid #ddd;color:#666;font-size:13px}}
code{{font-size:14px}}
</style>
</head>
<body>
<main>

<h1>QaraamiGen</h1>
<p class="sub">Adapting a text-to-music model to Somali qaraami from archival cassettes</p>
<p class="by">Khalid Ibrahim · Minneapolis, MN · {today.strftime("%B %Y")} · <a href="mailto:{CONTACT}">{CONTACT}</a></p>

<nav><a href="#audio">1. Audio examples</a><a href="#results">2. Results</a><a href="#harness">3. Training harness</a><a href="#method">4. Method</a>{'<a href="#dpo">5. Preference optimisation</a><a href="#rights">6. Rights</a>' if ctx["dpo"] else '<a href="#rights">5. Rights</a>'}</nav>

<p>Somali <i>qaraami</i> is a modally organised, mostly pentatonic song tradition that was transmitted
without notation and now survives largely on cassette. I have been working on two questions: whether
a general text-to-music model can be adapted to this material without the recordings leaving the
people who hold them, and what evidence would show that the adaptation learned the music rather than
the tape. This page collects the current state of that work. I fine-tuned MusicGen at three sizes
with low-rank adapters on 43 hours of held archival audio, evaluated the adapters on songs they had
not seen, and generated paired examples in which the base model and the adapter receive the same
prompt and the same random seed.</p>

<p>In summary: with the training harness corrected (Section 3), every checkpoint of every run improves
on its base model on held-out songs. The improvement is larger for larger models, {mg:.3f} nats of
per-song test cross-entropy for MusicGen-medium and {lgn:.3f} for MusicGen-large, with bootstrap
intervals over songs that exclude zero. The adapters also change what the models generate: their
output contains more pitched, trackable melody than the base models' (about twice as much for the
large model) and carries the tuning offset of the cassettes, while conforming somewhat less closely
to a pentatonic set. Whether the result sounds like qaraami is a matter for listening, so the audio
comes first.</p>

<p class="note">All audio on this page is model output. None of the training recordings is included,
and the adapters are not distributed (Section {6 if ctx["dpo"] else 5}).</p>

<h2 id="audio">1. Audio examples</h2>

<p>Each row is one prompt. The base model and the adapter receive the same text and the same random
seed; the only difference is the adapter weights. Below each clip are two measurements from its pitch
track. <b>PCS</b> is the duration-weighted fraction of pitched frames within 50 cents of the
best-fitting anhemitonic pentatonic set after a per-clip tuning fit. The <b>voiced fraction</b> is the
share of frames with a trackable pitch. The two are meant to be read together, since a model that
produces little melody can score high conformity on what remains. Prompts are captions from the
held-out test split. The catalogue-derived prompts include performer credits from the Harvard finding
aid, which I have removed from the captions shown here.</p>

<h3>1.1 MusicGen-medium (1.5 B) and MusicGen-large (3.3 B), 15-second clips</h3>
<p class="note">Eight of the sixteen prompts in the A/B set: the four synthetic qaraami prompts and the
first four catalogue prompts. The selection was fixed before any listening. Both sizes were trained on
the same {sc["total_clips"]:,} clips and generated from the same prompts and seeds, so the four columns
of a row are directly comparable.</p>
<div class="wrap">{scale_table}</div>

<h3>1.2 MusicGen-small (0.6 B), one collection per adapter, 10-second clips</h3>
<p class="note">The first two adapters, rank-16 LoRA on the decoder attention projections, each trained
on a single collection. First four pairs of each eight-pair listening set.</p>
{"".join(small_tables)}

<h3>1.3 Checkpoints during training, MusicGen-large</h3>
<p class="note">The same held-out prompt and seed generated at successive checkpoints:
<i>{esc(strip_credit(ctx["prog_caption"]))}</i>.</p>
<div class="wrap">{prog_table}</div>

<h3>1.4 Melody conditioning, preliminary</h3>
<p class="note">MusicGen-melody without an adapter, conditioned on the chroma of a held-out recording
rather than on text alone. This is the conditioning path a melody adapter would use; the reference
recordings are not included. Three of eight clips, those with the highest voiced fraction.</p>
<div class="wrap">{mel_table}</div>

<h2 id="results">2. Results</h2>

<h3>2.1 Scale runs</h3>
<p>Table 1 gives held-out per-song cross-entropy for the scale runs: {ln} unseen test songs
({el["test_clips"]} clips), base model against adapter, with a 95% bootstrap interval resampled over
songs. Clips from the same song share a cassette and a channel, so the song is the unit of
independence. PCS and voiced fraction are means over the 16-clip A/B set.</p>
<div class="wrap">{scale_results}</div>
<p>Cross-entropy improves at both sizes and the interval excludes zero in both cases. The gain is
larger for the large model, whose adapter reaches the lowest held-out cross-entropy measured so far.
On the generation side the large adapter roughly doubles the voiced fraction ({f3(vb)} to {f3(va)})
and lowers PCS ({f3(pb)} to {f3(pa)}). With sixteen prompts, PCS differences of this size are within
the scorer's run-to-run variation; the change in voiced fraction is well outside it.</p>

<figure>
<img src="figures/ft7_scale_val_curves.png" alt="Validation cross-entropy per checkpoint for the medium and large runs">
<figcaption>Figure 1. Validation token cross-entropy at every checkpoint of the medium and large runs
(48 validation clips, song-level split). Both curves flatten by about step 2,500; the best held-out
per-song test cross-entropy is at step 2,750 for both.</figcaption>
</figure>

<h3>2.2 Small runs</h3>
<p>Table 2 gives the MusicGen-small adapters, one collection each, trained on 15-second clips.
Validation and test are song-level splits and the test songs are unseen. Cross-entropy is not
comparable across corpora.</p>
<div class="wrap">{small_results}</div>
<figure>
<img src="figures/ft3_pcs_voiced.png" alt="PCS and voiced fraction for base, adapter and real clips on both corpora">
<figcaption>Figure 2. Pentatonic conformity and voiced fraction for base model, adapter and real
held-out clips, eight prompts per generated group. The adapters produce more melody than the base
model and, on both corpora, more than the real clips; conformity is similar (oud) or lower (Harvard).
They also learn the cassettes' tuning offset: base output sits near A440, adapter output about 25
cents away, as the tapes are.</figcaption>
</figure>

{listening_html(listening)}

<h3>Limitations</h3>
<ul>
<li>{listening_limit}</li>
<li>Clips are 10 to 15 seconds. Nothing here speaks to long-form structure.</li>
<li>Each adapter models the collections it was trained on, not Somali music in general.</li>
<li>The small-model margins are 0.5 to 3% and are reported without significance tests. Intervals
are given for the scale runs only.</li>
</ul>

<h2 id="harness">3. The training harness</h2>

<p>The first two months of fine-tuning gave a consistent negative result. At two learning rates and
on two corpora, held-out loss rose from 4.6 to about 6.7 nats within 250 steps and did not recover,
and the generations lost about half their melodic content. I had drafted that as a finding about
archival audio. It was a defect in the training harness.</p>

<figure>
<img src="figures/ft2_dropout_probe.png" alt="Train-mode versus eval-mode loss on identical weights">
<figcaption>Figure 3. A five-condition probe on identical zero-initialised LoRA weights. Eval-mode loss
is 4.05 nats; train-mode loss is 9.74, worse than uniform random over the 2,048-token codebook (7.62).
Setting every <code>nn.Dropout</code> module to zero (C), disabling gradient checkpointing (D), or
putting the encoders in eval mode (E) changes nothing.</figcaption>
</figure>

<p>The Hugging Face implementation of the MusicGen decoder applies dropout functionally, through 37
floating-point attributes passed to <code>F.dropout</code> with <code>training=self.training</code>.
A sweep that sets the rate of every <code>nn.Dropout</code> module to zero does not reach them. In
training mode, therefore, the model was being optimised on a forward path that evaluation never used.
Setting those attributes to zero makes the two paths identical. The first corrected run improved on
the base model at every checkpoint, and the Harvard corpus, which had produced the clearest negative,
did the same. The medium and large decoders have 61 such attributes. I report the defect here because
it is a property of the model family rather than of this project.</p>

<figure>
<img src="figures/ft1_val_curves.png" alt="Validation curves under the broken and the fixed harness">
<figcaption>Figure 4. Validation cross-entropy for every MusicGen-small run. Dashed: the original
harness, both corpora, all learning rates. Solid: the corrected harness. Dotted: the base model.</figcaption>
</figure>

<h2 id="method">4. Method</h2>

<h3>4.1 Data</h3>
<p>Three held collections of Somali qaraami, 43.1 hours in all, none cleared for public release: the
Maryan "Aryette" Omar Ali Collection at Harvard's Archive of World Music (22.6 h, mid-century ensemble
song on cassette), a privately shared oud-led collection (5.4 h, 28 songs, performers unlisted), and
15.1 h of qaraami recordings recovered from my own session archives. For the scale runs I cut the
audio into 30-second clips at 32 kHz mono and split it by song, so that no song appears in two splits:
{sc["clips"]["train"]:,} training clips from {sc["songs"]["train"]} songs, {sc["clips"]["val"]:,}
validation clips from {sc["songs"]["val"]}, and {sc["clips"]["test"]:,} test clips from
{sc["songs"]["test"]}. Captions are measured rather than written: tempo from the audio, tonic from the
pentatonic fit, instrumentation and era from the catalogue.</p>

<h3>4.2 Models and training</h3>
<div class="wrap"><table>
<thead><tr><th></th><th>MusicGen-small</th><th>MusicGen-medium</th><th>MusicGen-large</th></tr></thead>
<tbody>
<tr><td>parameters</td><td>{PARAMS["small"]}</td><td>{PARAMS["medium"]}</td><td>{PARAMS["large"]}</td></tr>
<tr><td>LoRA</td><td>r 16, α 32, attention q/k/v/out</td><td>r {m["cfg"]["rank"]}, α {m["cfg"]["alpha"]}, attention and FFN (q/k/v/out, fc1, fc2)</td><td>r {cfg["rank"]}, α {cfg["alpha"]}, attention and FFN</td></tr>
<tr><td>trainable</td><td>6.3 M</td><td>{TRAINABLE["medium"]}</td><td>{TRAINABLE["large"]}</td></tr>
<tr><td>clips</td><td>15 s, one collection</td><td>30 s, all three</td><td>30 s, all three</td></tr>
<tr><td>schedule</td><td>lr 1e-4 cosine, 1,000 to 3,000 steps</td><td>lr {m["cfg"]["lr"]:g} cosine, {m["cfg"]["total_steps"]:,} steps, {m["cfg"]["warmup"]} warm-up</td><td>lr {cfg["lr"]:g} cosine, {cfg["total_steps"]:,} steps, {cfg["warmup"]} warm-up</td></tr>
<tr><td>batch</td><td>1 × 4 accumulation</td><td>1 × {m["cfg"]["grad_accum"]}</td><td>1 × {cfg["grad_accum"]}</td></tr>
<tr><td>compute</td><td>Apple M1 / M5 Max, fp32 on MPS</td><td>M5 Max, {STEP_RATE["medium"]}/step, {PEAK_MEM["medium"]} peak</td><td>M5 Max, {STEP_RATE["large"]}/step, {PEAK_MEM["large"]} peak</td></tr>
<tr><td>dropout attributes zeroed</td><td>37</td><td>61</td><td>61</td></tr>
</tbody></table></div>
<p>All training ran on one laptop in fp32 on Apple silicon, from precomputed EnCodec tokens with
delay-pattern labels. Base weights are unchanged. A local inference service hot-swaps the adapters
and labels every generation with the adapter's training corpus and a non-distribution notice.</p>

<h3>4.3 Evaluation</h3>
<p>Two kinds of measurement. <b>Likelihood:</b> token cross-entropy on unseen songs, averaged within
each song and then across songs, with the confidence interval bootstrapped over songs. The song is
the right unit on archival audio; in an embedding audit of this corpus, nearest neighbours retrieved
same-cassette material at thirteen times chance, so clip-level splits leak the channel.
<b>Output:</b> PCS and voiced fraction from a CREPE pitch track over the generated audio, using the
same scorer I use to measure intonation in the recordings themselves, together with paired A/B sets
for listening. I report PCS only alongside the voiced fraction and treat it as a direction rather
than a statistic at these sample sizes.</p>

{dpo_html(ctx["dpo"], ctx["clips"], listening)}

<h2 id="rights">{6 if ctx["dpo"] else 5}. Rights and provenance</h2>
<p>The Harvard collection is not rights-cleared for redistribution and my request for written
permission from the Loeb Music Library is pending. The oud collection's rights remain with its
performers, who are not named. The third source is of mixed and partly unknown provenance. All three
are used for training and measurement only. No recording from any of them appears on this page, in
the repository, or in any public artifact, and the adapters, which are derived from them, are not
distributed. The clips here are the outputs of models conditioned on text, generated for evaluation,
and are labelled as such wherever they appear. Per-collection status and the outstanding items are
documented in the repository's provenance file.</p>

<footer>
Last updated {today.isoformat()}. Code, model cards, the evaluation report and the paper draft are
available on request.
</footer>

</main>
</body>
</html>
"""


def inline_assets(page: str) -> str:
    def data_uri(rel: str) -> str:
        p = OUT / rel
        mime = "audio/mpeg" if p.suffix == ".mp3" else "image/png"
        return f"data:{mime};base64,{base64.b64encode(p.read_bytes()).decode('ascii')}"
    return re.sub(r'src="((?:audio|figures)/[^"]+)"', lambda mm: f'src="{data_uri(mm.group(1))}"', page)


# -------------------------------------------------------------------- main

def main() -> None:
    scale = {tag: load_scale(tag) for tag in ("medium", "large")}
    scale_captions = read_captions(DATA / "ab_large")
    best_step = int(scale["large"]["eval"]["best_ckpt"].split("_")[-1])
    prog_steps = PROGRESSION_STEPS + [best_step]

    clips: dict[str, Clip] = {}
    for tag in ("medium", "large"):
        pairs = {p["pair"]: p for p in scale[tag]["eval"]["ab"]["pairs"]}
        for i in SCALE_PAIRS:
            for side in ("base", "adapter"):
                sc = pairs[i][side]
                clips[f"{tag}_{i:03d}_{side}"] = Clip(
                    DATA / f"ab_{tag}" / f"pair{i:03d}_{side}.wav", f"{tag}_{i:03d}_{side}",
                    sc.get("pcs") if sc.get("scored") else None,
                    sc.get("voiced_fraction") if sc.get("scored") else None)
    small_captions, small_summary = {}, {}
    for key, info in SMALL.items():
        d = DATA / info["set"]
        small_captions[key] = read_captions(d)
        rows = {side: pcs_csv(name) for side, name in zip(("base", "adapter"), info["csv"])}
        for i in SMALL_PAIRS:
            for side, fname in (("base", "base"), ("adapter", "finetuned")):
                r = rows[side].get(i, {})
                clips[f"{key}_{i:03d}_{side}"] = Clip(
                    d / f"pair{i:03d}_{fname}.wav", f"{key}_{i:03d}_{side}",
                    num(r.get("pcs")), num(r.get("voiced_fraction")))
        summ = {}
        for side, name in zip(("base", "adapter"), info["csv"]):
            g = json.loads((DATA / "eval_pcs" / f"{name}.json").read_text())
            summ[f"pcs_{side}"] = g["pcs_mean"]
            summ[f"voiced_{side}"] = g["voiced_fraction_mean"]
        small_summary[key] = summ
    for s in prog_steps:
        clips[f"large_step{s:04d}"] = Clip(RUNS / "qaraami_large_r32/samples" / f"step_{s:04d}.wav", f"large_step{s:04d}")
    mel = json.loads((DATA / "ab_melody/melody_condition.json").read_text())
    melody_clips = []
    for c in sorted(mel["clips"], key=lambda c: -c["voiced_fraction"])[:N_MELODY]:
        clip = Clip(DATA / "ab_melody" / c["file"], f"melody_{c['i']:03d}", c["pcs"], c["voiced_fraction"])
        clips[clip.name] = clip
        melody_clips.append(clip)

    dpo = dpo_results()
    if dpo:
        passing = [s for s in dpo if dpo_ok(s["eval"])]
        top = (passing or dpo)[-1]
        for row in top["scores"]["pairs"][:N_DPO_PAIRS]:
            i = row["pair"]
            for side in ("base", "adapter"):
                src = top["ab_dir"] / f"pair{i:03d}_{side}.wav"
                if src.exists():
                    sc = row.get(side) or {}
                    clips[f'dpo_{top["tag"]}_{i:03d}_{side}'] = Clip(src, f'dpo_{top["tag"]}_{i:03d}_{side}', sc.get("pcs"), sc.get("voiced_fraction"))

    missing = [c.src for c in clips.values() if not c.src.exists()]
    if missing:
        sys.exit("missing source clips:\n  " + "\n  ".join(map(str, missing)))

    OUT.mkdir(parents=True, exist_ok=True)
    transcode(list(clips.values()))
    figure_scale_val({tag: scale[tag]["val_curve"] for tag in scale})
    FIGOUT.mkdir(exist_ok=True)
    for name in ("ft1_val_curves", "ft2_dropout_probe", "ft3_pcs_voiced", "ft7_scale_val_curves"):
        shutil.copy2(FIG / f"{name}.png", FIGOUT / f"{name}.png")

    ctx = {
        "scale": scale, "scale_captions": scale_captions, "clips": clips, "best_step": best_step,
        "prog_steps": prog_steps, "prog_caption": (RUNS / "qaraami_large_r32/sample_caption.txt").read_text().strip(),
        "melody_clips": melody_clips, "small_captions": small_captions, "small_summary": small_summary,
        "splits": split_counts(), "listening": listening_results(), "dpo": dpo,
    }
    page = build_html(ctx)
    (OUT / "index.html").write_text(page, encoding="utf-8")
    bundle = OUT / "QaraamiGen-demo.html"
    bundle.write_text(inline_assets(page), encoding="utf-8")

    mb = sum((AUDIO / f"{c.name}.mp3").stat().st_size for c in clips.values()) / 1e6
    print(f"{len(clips)} clips, {mb:.1f} MB of audio -> {OUT.relative_to(REPO)}/index.html")
    if ctx["listening"]:
        print("listening results:", ", ".join(f"{k}: {v['adapter']}/{v['n']}" for k, v in ctx["listening"].items()))
    else:
        print("no listening results in data/listening/ yet; page says the study is pending")
    print(f"single file: {bundle.relative_to(REPO)} ({bundle.stat().st_size / 1e6:.1f} MB)")


if __name__ == "__main__":
    main()
