"""Render docs/eval/PREFERENCE_OPT.md, the Stage 5 report, from the artifacts on disk.

Sources: data/reward/calibration.json and oud_ref.json (reward model),
data/listening/*.json (blind tests), runs/dpo_<tag>/{config,eval_round_*}.json and
round_*/train_log.csv (each preference round). Nothing in the report is typed by
hand; rerun after every stage.

Usage (from apps/ai-service):
  python -m scripts.dpo_report
"""
from __future__ import annotations

import csv
import json
import math
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
DATA = REPO / "data"
RUNS = REPO / "runs"
OUT = REPO / "docs/eval/PREFERENCE_OPT.md"
STAGES = ("small_oud", "medium", "large")
LABEL = {"small_oud": "small, oud adapter", "medium": "medium", "large": "large"}


def f(x, nd=3):
    return "–" if x is None else f"{x:.{nd}f}"


def wilson(k, n, z=1.96):
    if not n:
        return (0.0, 0.0)
    p = k / n
    d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return (c - h, c + h)


def listening_rows():
    rows = []
    d = DATA / "listening"
    if not d.is_dir():
        return rows
    for p in sorted(d.glob("*.json")):
        r = json.loads(p.read_text())
        s = r.get("summary") or {}
        if s.get("n"):
            lo, hi = wilson(s["adapter"], s["n"])
            rows.append(f"| {r['set']} | {r.get('listener','')} | {r.get('date','')[:10]} | {s['n']} | {s['adapter']} | {s['base']} | {s['none']} | {s['adapter']/s['n']:.2f} [{lo:.2f}, {hi:.2f}] |")
    return rows


def stage_block(tag: str) -> str:
    run = RUNS / f"dpo_{tag}"
    ev = run / "eval_round_1.json"
    if not ev.exists():
        return f"### {LABEL[tag]}\n\nNot run yet.\n"
    e = json.loads(ev.read_text())
    cfg = json.loads((run / "config.json").read_text())
    log = list(csv.DictReader((run / "round_1/train_log.csv").open()))
    last = log[-1] if log else {}
    tail = log[-10:] if log else []
    acc = sum(float(r["acc"]) for r in tail) / max(1, len(tail))
    b, a = e["before"], e["after"]
    ce = e["held_out_oud_token_ce"]
    fad = e["fad_to_real_oud_test"]
    keys = [k for k in ("reward", "oud_dist", "oud_sim", "band_snr_db", "pcs", "voiced_fraction", "noise_floor_db") if k in b]
    lines = [f"### {LABEL[tag]}", "",
             f"`{cfg['model']}` from `{Path(cfg['adapter']).parent.name}/{Path(cfg['adapter']).name}`; "
             f"{e['prompts']} prompts × {cfg['samples_per_prompt']} samples of {cfg['seconds']} s → {e['pairs']} pairs "
             f"(margin {cfg['margin']} z); DPO β {cfg['beta']} on {cfg['logp_norm']} token log-probs, lr {cfg['lr']:g}, "
             f"{cfg['epochs']} epochs, {e['steps']} steps"
             + (f", likelihood anchor {cfg['sft_weight']}" if cfg.get('sft_weight') else "") + ". "
             f"Sampling {e['gen_minutes']} min, training {e['train_minutes']} min, eval {e['eval_minutes']} min.", "",
             "| measure | before | after | note |", "| --- | --- | --- | --- |"]
    notes = {"reward": "composite, z-scored over the union of both sides",
             "oud_dist": "Mahalanobis distance to the real oud clips (real train 4.20, test 4.13)",
             "oud_sim": "cosine to the real-oud centroid", "band_snr_db": "3–10 kHz band SNR (real cassette 4.5, real oud 8.3)",
             "pcs": "pentatonic conformity", "voiced_fraction": "trackable melody", "noise_floor_db": "10th-percentile frame RMS"}
    for k in keys:
        lines.append(f"| {k} | {f(b.get(k))} | {f(a.get(k))} | {notes.get(k, '')} |")
    lines.append(f"| MERT-FAD to real oud test | {f(fad.get('before'))} | {f(fad.get('after'))} | {e.get('prompts', '')} eval prompts per side; indicative only at n = 40 in 32-d |")
    lines.append(f"| held-out oud token CE | {f(ce['before'], 4)} | {f(ce['after'], 4)} | {ce['clips']} unseen-song clips; the collapse guard |")
    lines += ["", f"Training curve: final DPO loss {last.get('loss', '–')}, implicit-reward margin {last.get('margin', '–')} "
              f"(β × per-token log-ratio difference), pair accuracy over the last ten steps {acc:.2f}; "
              f"chosen log-ratio {last.get('chosen_logratio', '–')}, rejected {last.get('rejected_logratio', '–')} nats per token.",
              "", f"Blind test set: `data/ab_dpo_{tag}/` (pairNNN_base = before, pairNNN_adapter = after, same prompt and seed).", ""]
    return "\n".join(lines)


def main() -> None:
    cal = json.loads((DATA / "reward/calibration.json").read_text()) if (DATA / "reward/calibration.json").exists() else {}
    ref = json.loads((DATA / "reward/oud_ref.json").read_text()) if (DATA / "reward/oud_ref.json").exists() else {}
    groups = cal.get("groups") or cal.get("calibration") or {}
    out = ["# Preference optimisation toward clean oud qaraami (Stage 5)", "",
           "*Generated by `apps/ai-service/scripts/dpo_report.py` from the run artifacts; rerun after every stage.*", "",
           "## Why", "",
           "The supervised adapters learn the corpus as recorded, tape hiss included. In the blind test on the large adapter "
           "the adapter was preferred, and called noisy. Stage 5 keeps the adapters and changes what they are optimised for: "
           "closeness to the real oud recordings, less hiss, more trackable pentatonic melody. No new recordings are used.", "",
           "## Method", "",
           "Direct preference optimisation on the LoRA adapter (`scripts/dpo_train.py`). Per round: K samples for each of P prompts "
           "from the oud caption grammar (lead instrument × tempo × pentatonic tonic), re-encoded with the model's own EnCodec; "
           "the composite reward (`scripts/reward_model.py`) ranks them; best-vs-worst pairs above a margin; the reference policy is "
           "the adapter at the start of the round, its log-probabilities cached; DPO loss on length-normalised token log-probabilities "
           "with every module dropout zeroed so policy and reference are the same function of the weights (at step 1 the loss is ln 2 "
           "and the margin 0, as it must be). Evaluation on 40 held-out prompts: reward terms, MERT-FAD to the 276 real oud test clips, "
           "held-out oud token cross-entropy as a collapse guard, and an A/B set for the blind listening test.", "",
           "### Reward", "",
           "* **oud_dist**: Mahalanobis distance in a 32-d PCA space of MERT-v1-95M embeddings fitted on the "
           f"{ref.get('n_train', 1512)} real oud training clips (PCA explains {ref.get('pca_explained', 0.964) * 100:.1f}% of variance)"
           if isinstance(ref.get('pca_explained'), float) else
           "* **oud_dist**: Mahalanobis distance in a 32-d PCA space of MERT-v1-95M embeddings fitted on the 1,512 real oud training clips",
           "* **band_snr_db**: median minus 10th-percentile energy of the 3–10 kHz band across frames; stationary hiss fills that band "
           "in quiet moments. Real cassette 4.5 dB, real oud 8.3, base MusicGen 10.4. On the 7 blind pairs annotated \"noisy\", "
           "the noisy clip reads 4.3 dB against 11.6 for the other.",
           "* **melody**: PCS × min(voiced fraction, 0.6)/0.6, from the project's pitch scorer; a penalty for clips with < 15% voiced frames.",
           "* composite R = z(−oud_dist) + 0.5 z(−hiss) + 0.5 z(melody) − 2·[near-silent], z-scored within the scored pool.", ""]
    if groups:
        out += ["### Calibration (`data/reward/calibration.json`)", "",
                "| group | n | oud_dist | band_snr_db | pcs | voiced | composite | FAD→real oud |", "| --- | --- | --- | --- | --- | --- | --- | --- |"]
        for name, g in groups.items():
            m = g.get("means") or g
            out.append(f"| {name} | {g.get('n', '')} | {f(m.get('oud_dist'), 2)} | {f(m.get('band_snr_db'), 1)} | {f(m.get('pcs'))} | "
                       f"{f(m.get('voiced_fraction'))} | {f(m.get('reward'), 2)} | {f(g.get('fad'), 3)} |")
        out.append("")
    lc = cal.get("listener_check") or {}
    if lc:
        out += ["### Agreement with the blind test", "",
                f"Over the decided pairs of the large-adapter blind test: {json.dumps(lc)[:600]}", ""]
    out += ["## Blind listening tests on record", "",
            "| set | listener | date | pairs | adapter | base | neither | adapter rate [95% CI] |", "| --- | --- | --- | --- | --- | --- | --- | --- |"]
    out += listening_rows() or ["| – | | | | | | | |"]
    out += ["", "## Rounds", ""]
    for tag in STAGES:
        out.append(stage_block(tag))
    out += ["## Reading the numbers", "",
            "A fall in oud_dist toward the real clips' 4.1–4.2 with band SNR rising toward or past the real oud clips' 8.3 dB is the intended "
            "effect. A rise in held-out token CE means the policy is a worse density model of the corpus than the adapter it started from; "
            "DPO trades likelihood for preference and the size of that trade is reported, not hidden. The reward can be won without "
            "winning a listener: the before/after blind test on each `data/ab_dpo_<tag>/` set is the arbiter.", ""]
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
