"""Systematic-error report over the transcription pool.

    python -m scripts.pool_report [--pool-dir ../../data/transcription_pool]
        [--out ../../docs/eval/TRANSCRIPTION_POOL_REPORT.md]

Reads pool_index.json and writes a Markdown report of what the pipeline did
across the collection: tonic and mode distributions, how often the tonic was
ambiguous, where each scale degree sits relative to 12-TET across recordings
(the microtonal finding, given with counts and spread), the PCS distribution,
and the recordings where the pipeline looks least reliable and why. Numbers
only; the reader draws the conclusions.
"""
from __future__ import annotations

import argparse
import json
import statistics as st
import sys
from collections import Counter, defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
PC_NAMES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]
MODE_INTERVALS = {0: "0/200/400/700/900", 1: "0/200/500/700/1000", 2: "0/300/500/800/1000",
                  3: "0/200/500/700/900", 4: "0/300/500/700/1000"}
AMBIGUITY_RATIO = 0.95
FLAGS = {
    "low_pcs": ("PCS below 0.85", lambda r: r.get("pcs") is not None and r["pcs"] < 0.85),
    "few_notes": ("under 20 notes per minute of audio", lambda r: r.get("n_notes") is not None
                  and r["n_notes"] / max(_minutes(r), 1e-6) < 20),
    "many_marked": ("over 15 percent of notes kept off-scale", lambda r: r.get("n_notes")
                    and r["n_marked"] / r["n_notes"] > 0.15),
    "quiet_voice": ("voice stem voiced under 15 percent of the time", lambda r: r.get("voice_voiced_fraction") is not None
                    and r["voice_voiced_fraction"] < 0.15),
    "ambiguous": ("tonic ambiguous (runner-up within 5 percent)", lambda r: bool(r.get("tonic_ambiguous"))),
    "unrefined": ("a scale degree too sparse to refine", lambda r: r.get("degree_refined") and not all(r["degree_refined"])),
}


def content_key(r: dict) -> str:
    """source + content-hash prefix: the slug is <source>_<sha8>_<name>."""
    parts = r["slug"].split("_", 2)
    if len(parts) < 3:
        return r["slug"]  # not a pool slug: its own recording
    return f"{parts[0]}_{parts[1]}"


def fold_duplicates(rows: list[dict]) -> tuple[list[dict], int]:
    """One row per recording by content: files with identical audio but
    different names entered the pool under different slugs. Keeps the first
    row per (source, hash) in slug order; returns (rows, number folded)."""
    seen: set[str] = set()
    out = []
    for r in sorted(rows, key=lambda r: r["slug"]):
        k = content_key(r)
        if k in seen:
            continue
        seen.add(k)
        out.append(r)
    return out, len(rows) - len(out)


def _minutes(r: dict) -> float:
    d = r.get("excerpt_sec") or r.get("duration_s") or 0.0
    return float(d) / 60.0


def _stats(xs: list[float]) -> dict:
    if not xs:
        return {"n": 0}
    xs = sorted(xs)
    q = st.quantiles(xs, n=4) if len(xs) >= 4 else [xs[0], st.median(xs), xs[-1]]
    return {"n": len(xs), "mean": st.mean(xs), "sd": st.pstdev(xs) if len(xs) > 1 else 0.0,
            "median": st.median(xs), "q1": q[0], "q3": q[-1], "min": xs[0], "max": xs[-1]}


def _fmt(s: dict, d: int = 1) -> str:
    if s["n"] == 0:
        return "n = 0"
    return (f"n = {s['n']}, mean {s['mean']:+.{d}f}, sd {s['sd']:.{d}f}, median {s['median']:+.{d}f}, "
            f"IQR {s['q1']:+.{d}f} to {s['q3']:+.{d}f}, range {s['min']:+.{d}f} to {s['max']:+.{d}f}")


def build_report(rows: list[dict], title_date: str, note: str | None = None) -> str:
    rows, folded = fold_duplicates(rows)
    ok = [r for r in rows if not r.get("error")]
    failed = [r for r in rows if r.get("error")]
    by_src = defaultdict(list)
    for r in ok:
        by_src[r["source"]].append(r)
    L = [f"# Transcription pool report ({title_date})", "",
         "Generated by `scripts/pool_report.py` from `data/transcription_pool/pool_index.json`. "
         "Every figure below is computed from the pipeline's own output; nothing is hand-typed. "
         "The pool is the candidate benchmark pool, not the benchmark: no recording has been corrected by ear yet, "
         "so these are properties of the automatic transcriptions, not of the music, except where a reader "
         "judges the pipeline reliable enough for the distinction not to matter.", "",
         "## Coverage", "",
         f"- {len(rows)} recordings attempted, {len(ok)} transcribed, {len(failed)} failed.",
         "- " + "; ".join(f"{src}: {len(rs)} recordings, {sum(r['duration_s'] for r in rs) / 3600:.1f} h of source audio"
                          + (f" ({sum(r.get('excerpt_sec') or r['duration_s'] for r in rs) / 60:.0f} min transcribed as excerpts)" if any(r.get('excerpt_sec') for r in rs) else "")
                          for src, rs in sorted(by_src.items())) + ".",
         f"- Pipeline time {sum(r['runtime_s'] for r in rows) / 3600:.1f} h on the CPU (CREPE on the CPU, Demucs on the GPU)."]
    if folded:
        L.append(f"- {folded} pool rows were files with the same audio as another file under a different name; "
                 f"each such recording is counted once here.")
    if note:
        L.append(f"- {note}")
    if failed:
        L += ["", "Failed:", ""] + [f"- `{r['slug']}`: {r['error']}" for r in failed]

    # tonic + mode
    L += ["", "## Tonic and mode", "", "| tonic | all | " + " | ".join(sorted(by_src)) + " |", "| --- | --- | " + " | ".join("---" for _ in by_src) + " |"]
    tonics = Counter(r["tonic"] for r in ok)
    for pc in PC_NAMES:
        if tonics[pc]:
            L.append(f"| {pc} | {tonics[pc]} | " + " | ".join(str(sum(1 for r in by_src[s] if r['tonic'] == pc)) for s in sorted(by_src)) + " |")
    modes = Counter(r["mode"] for r in ok)
    L += ["", "| mode | intervals (cents above tonic) | recordings |", "| --- | --- | --- |"]
    for m in range(5):
        L.append(f"| {m} | {MODE_INTERVALS[m]} | {modes.get(m, 0)} |")
    amb = [r for r in ok if r.get("tonic_ambiguous")]
    ratios = [r["ratio_to_winner"] for r in ok if r.get("ratio_to_winner") is not None]
    L += ["", "## Tonic ambiguity", "",
          f"- Runner-up tonic within 5 percent of the winner (score ratio at or above {AMBIGUITY_RATIO}): "
          f"{len(amb)} of {len(ok)} recordings ({100 * len(amb) / max(len(ok), 1):.0f} percent).",
          f"- Score ratio of the best other-tonic reading to the winner: {_fmt(_stats(ratios), 3)}."]
    if amb:
        L += ["", "| recording | reading | ratio |", "| --- | --- | --- |"]
        L += [f"| `{r['slug']}` | {r['tonic_label']} | {r['ratio_to_winner']:.3f} |" for r in sorted(amb, key=lambda r: -r['ratio_to_winner'])]

    # microtonal: deviations by template interval
    dev_by_interval: dict[int, list[float]] = defaultdict(list)
    dev_by_interval_src: dict[tuple[int, str], list[float]] = defaultdict(list)
    dev_by_index: dict[int, list[float]] = defaultdict(list)
    unrefined = Counter()
    for r in ok:
        sc, tp, ref = r.get("scale_cents"), r.get("scale_cents_template"), r.get("degree_refined")
        if not (sc and tp and ref):
            continue
        for i in range(1, len(tp)):
            if not ref[i]:
                unrefined[int(round(tp[i]))] += 1
                continue
            d = ((sc[i] - tp[i]) + 600.0) % 1200.0 - 600.0
            dev_by_interval[int(round(tp[i]))].append(d)
            dev_by_interval_src[(int(round(tp[i])), r["source"])].append(d)
            dev_by_index[i].append(d)
    L += ["", "## Where the scale degrees sit relative to 12-TET", "",
          "Each recording's degrees were refined to the weighted median of its own pitches within 60 cents "
          "of the 12-TET template (`refine_scale_cents`), after removing the recording's overall tuning offset. "
          "The deviation below is refined position minus template, in cents, grouped by the template interval "
          "above the tonic so that the same interval is compared across modes. A degree with under 2 percent of "
          "the pitch mass is not refined and is counted separately. The tonic is 0 by construction and is not listed.", "",
          "| interval (cents) | deviation from 12-TET (cents) | not refined |", "| --- | --- | --- |"]
    for iv in sorted(set(dev_by_interval) | set(unrefined)):
        L.append(f"| {iv} | {_fmt(_stats(dev_by_interval.get(iv, [])))} | {unrefined.get(iv, 0)} |")
    L += ["", "By source:", "", "| interval | source | deviation from 12-TET (cents) |", "| --- | --- | --- |"]
    for (iv, src) in sorted(dev_by_interval_src):
        L.append(f"| {iv} | {src} | {_fmt(_stats(dev_by_interval_src[(iv, src)]))} |")
    L += ["", "By degree index (1 = second degree above the tonic, ascending):", "",
          "| degree | deviation from 12-TET (cents) |", "| --- | --- |"]
    for i in sorted(dev_by_index):
        L.append(f"| {i} | {_fmt(_stats(dev_by_index[i]))} |")
    offs = [r["tuning_offset_cents"] for r in ok if r.get("tuning_offset_cents") is not None]
    L += ["", f"Overall tuning offset from A440 (tape speed and instrument tuning together): {_fmt(_stats(offs))}."]

    # PCS
    L += ["", "## Pentatonic conformity of the kept notes", ""]
    L.append(f"- All recordings: {_fmt(_stats([r['pcs'] for r in ok if r.get('pcs') is not None]), 3)}.")
    for src in sorted(by_src):
        L.append(f"- {src}: {_fmt(_stats([r['pcs'] for r in by_src[src] if r.get('pcs') is not None]), 3)}.")
    voice = [r["pcs_voice"] for r in ok if r.get("pcs_voice") is not None]
    oud = [r["pcs_oud"] for r in ok if r.get("pcs_oud") is not None and r.get("pcs_voice") is not None]
    if voice:
        L.append(f"- Separated recordings, voice staff: {_fmt(_stats(voice), 3)}; oud staff of the same recordings: {_fmt(_stats(oud), 3)}.")
    vv = [r["voice_voiced_fraction"] for r in ok if r.get("voice_voiced_fraction") is not None]
    if vv:
        L.append(f"- Voice stem voiced fraction (share of frames with a confident pitch): {_fmt(_stats(vv), 2)}.")
    npm = [r["n_notes"] / _minutes(r) for r in ok if r.get("n_notes") and _minutes(r) > 0]
    L.append(f"- Kept notes per minute of audio: {_fmt(_stats(npm))}.")
    marked = [r["n_marked"] / r["n_notes"] for r in ok if r.get("n_notes")]
    L.append(f"- Share of kept notes left off-scale and marked: {_fmt(_stats([100 * m for m in marked]))} percent.")

    # least reliable
    flagged = []
    for r in ok:
        hits = [FLAGS[k][0] for k in FLAGS if FLAGS[k][1](r)]
        if hits:
            flagged.append((len(hits), r, hits))
    flagged.sort(key=lambda t: (-t[0], t[1]["slug"]))
    L += ["", "## Where the pipeline looks least reliable", "",
          "Recordings with at least one warning sign. The signs are mechanical: " +
          "; ".join(v[0] for v in FLAGS.values()) + ". More signs, less trust; none of them proves an error.", "",
          "| recording | source | signs | PCS | notes/min | marked | voice voiced |", "| --- | --- | --- | --- | --- | --- | --- |"]
    for n, r, hits in flagged:
        vvf = r.get("voice_voiced_fraction")
        vv_cell = "" if vvf is None else f"{vvf:.2f}"
        L.append(f"| `{r['slug']}` | {r['source']} | {'; '.join(hits)} | {r.get('pcs', 0):.3f} | "
                 f"{r['n_notes'] / max(_minutes(r), 1e-6):.0f} | {100 * r['n_marked'] / max(r['n_notes'], 1):.0f}% | "
                 f"{vv_cell} |")
    for r in failed:
        L.append(f"| `{r['slug']}` | {r['source']} | failed: {r['error']} | | | | |")
    L += ["", f"{len(flagged)} of {len(ok)} transcribed recordings carry at least one sign; "
          f"{sum(1 for n, _, _ in flagged if n >= 2)} carry two or more.", ""]
    return "\n".join(L)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="systematic-error report over the transcription pool")
    ap.add_argument("--pool-dir", default=str(REPO / "data" / "transcription_pool"))
    ap.add_argument("--out", default=str(REPO / "docs" / "eval" / "TRANSCRIPTION_POOL_REPORT.md"))
    ap.add_argument("--date", default=None)
    ap.add_argument("--note", default=None, help="one extra sentence for the coverage section")
    a = ap.parse_args(argv)
    import time

    rows = json.loads((Path(a.pool_dir) / "pool_index.json").read_text())
    text = build_report(rows, a.date or time.strftime("%Y-%m-%d"), a.note)
    Path(a.out).write_text(text + "\n")
    print(f"wrote {a.out}: {len(rows)} rows")
    return 0


if __name__ == "__main__":
    sys.exit(main())
