"""Batch transcription of the candidate benchmark pool.

    python -m scripts.transcribe_pool [--sources oud band] [--band-excerpt-sec 90]
        [--pitch-device cpu] [--limit N] [--pool-dir ../../data/transcription_pool]

Reads the corpus inventories (data/inventory/<source>.jsonl): every oud
recording (instrumental, whole file) and every band recording the inventory
flags as carrying vocals (separated, an excerpt from the start). The Harvard
inventory is never read. One subprocess per recording, with a timeout, so a
bad file cannot stall the pool; already-finished items are skipped, so the
run can be resumed. After every item pool_index.json and INDEX.md are
rewritten, so progress is visible while it runs.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
SOURCES = {"oud": "oud_ilkacase", "band": "band_qaraami"}
ITEM_TIMEOUT_S = 3600


def slugify(name: str, limit: int = 40) -> str:
    s = re.sub(r"[^a-z0-9]+", "_", Path(name).stem.lower()).strip("_")
    return s[:limit].rstrip("_") or "item"


def load_items(sources: list[str]) -> list[dict]:
    items = []
    for key in sources:
        inv = REPO / "data" / "inventory" / f"{SOURCES[key]}.jsonl"
        if not inv.exists():
            print(f"no inventory for {key}: {inv}", file=sys.stderr)
            continue
        for line in inv.read_text().splitlines():
            if not line.strip():
                continue
            r = json.loads(line)
            if "error" in r or not r.get("duration_s"):
                continue
            if key == "band" and r.get("vocals") != "likely":
                continue
            items.append({"source": key, "name": r["name"], "path": r["path"],
                          "duration_s": float(r["duration_s"]),
                          "slug": f"{key}_{r['sha256_16'][:8]}_{slugify(r['name'])}"})
    return items


def row_from_result(item: dict, out: Path, runtime: float, error: str | None) -> dict:
    row = {"slug": item["slug"], "source": item["source"], "name": item["name"],
           "duration_s": round(item["duration_s"], 1), "runtime_s": round(runtime, 1), "error": error}
    js = sorted(out.glob("*.json"))
    js = [p for p in js if not p.name.endswith("pool_row.json")]
    if error or not js:
        return row
    d = json.loads(js[0].read_text())
    if "error" in d:
        row["error"] = d["error"]
        return row
    sc, st, q, pcs = d["scale"], d["stems"], d["quantization"], d["pcs_of_kept_notes"]
    voice = st.get("Voice")
    row.update({
        "artifact_stem": js[0].stem, "excerpt_sec": d.get("excerpt_sec"),
        "tonic": sc["tonic_name"], "tonic_label": sc["tonic_label"], "tonic_ambiguous": sc["tonic_ambiguous"],
        "runner_up": (sc.get("tonic_runner_up") or {}).get("tonic_name"),
        "ratio_to_winner": sc.get("tonic_ratio_to_winner"), "mode": sc["mode"],
        "scale_cents": sc["scale_cents"], "scale_cents_template": sc["scale_cents_template"],
        "degree_refined": sc["scale_degree_refined"], "degree_mass": sc["scale_degree_mass"],
        "tuning_offset_cents": sc["tuning_offset_cents"],
        "pcs": pcs.get("overall"), "pcs_voice": pcs.get("Voice"), "pcs_oud": pcs.get("Oud (kaban)"),
        "n_notes": q["n_notes"], "n_marked": q["n_marked_off_scale"],
        "n_voice_notes": voice["n_notes_kept"] if voice else None,
        "voice_voiced_fraction": voice["voiced_fraction"] if voice else None,
        "bpm": d["tempo"]["bpm"], "render": d["outputs"]["render"].get("renderer"),
    })
    return row


def write_index(pool: Path, rows: list[dict]) -> None:
    (pool / "pool_index.json").write_text(json.dumps(rows, indent=1))
    lines = ["# Transcription pool index", "",
             f"{len(rows)} recordings; {sum(1 for r in rows if r.get('error'))} failed. "
             "Generated by scripts/transcribe_pool.py; outputs in each slug's folder.", "",
             "| slug | source | duration | tonic (runner-up) | scale cents | PCS | notes | marked | voice voiced | runtime | failure |",
             "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"]
    for r in rows:
        if r.get("error"):
            lines.append(f"| {r['slug']} | {r['source']} | {r['duration_s']:.0f} s | | | | | | | {r['runtime_s']:.0f} s | {str(r['error'])[:80]} |")
            continue
        exc = f" (first {r['excerpt_sec']:.0f} s)" if r.get("excerpt_sec") else ""
        tonic = r["tonic_label"] + (" ambiguous" if r["tonic_ambiguous"] else (f" ({r['runner_up']})" if r.get("runner_up") else ""))
        vv = f"{r['voice_voiced_fraction']:.2f}" if r.get("voice_voiced_fraction") is not None else "n/a"
        lines.append(f"| {r['slug']} | {r['source']} | {r['duration_s']:.0f} s{exc} | {tonic} | "
                     f"{'/'.join(f'{c:.0f}' for c in r['scale_cents'])} | {r['pcs']:.3f} | {r['n_notes']} | {r['n_marked']} | {vv} | {r['runtime_s']:.0f} s | |")
    (pool / "INDEX.md").write_text("\n".join(lines) + "\n")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="batch transcription of the benchmark pool")
    ap.add_argument("--sources", nargs="*", default=["oud", "band"], choices=list(SOURCES))
    ap.add_argument("--band-excerpt-sec", type=float, default=90.0)
    ap.add_argument("--pitch-device", default="cpu")
    ap.add_argument("--limit", type=int, default=0, help="per source, for a smoke run")
    ap.add_argument("--pool-dir", default=str(REPO / "data" / "transcription_pool"))
    a = ap.parse_args(argv)
    pool = Path(a.pool_dir)
    pool.mkdir(parents=True, exist_ok=True)
    items = load_items(a.sources)
    if a.limit:
        items = [it for key in a.sources for it in [x for x in items if x["source"] == key][: a.limit]]
    index_path = pool / "pool_index.json"
    rows = json.loads(index_path.read_text()) if index_path.exists() else []
    done = {r["slug"] for r in rows if not r.get("error")}
    todo = [it for it in items if it["slug"] not in done]
    print(f"pool: {len(items)} items, {len(done)} done, {len(todo)} to run", flush=True)
    t_all = time.time()
    for i, it in enumerate(todo, 1):
        out = pool / it["slug"]
        out.mkdir(exist_ok=True)
        cmd = [sys.executable, "-m", "scripts.transcribe", it["path"], "--out", str(out),
               "--pitch-device", a.pitch_device]
        if it["source"] == "oud":
            cmd.append("--instrumental")
        else:
            cmd += ["--excerpt-sec", str(a.band_excerpt_sec)]
        t0 = time.time()
        error = None
        try:
            proc = subprocess.run(cmd, capture_output=True, text=True, timeout=ITEM_TIMEOUT_S,
                                  cwd=Path(__file__).resolve().parents[1])
            if proc.returncode != 0:
                error = proc.stderr.strip().splitlines()[-1][:300] if proc.stderr.strip() else f"exit {proc.returncode}"
        except subprocess.TimeoutExpired:
            error = f"timeout after {ITEM_TIMEOUT_S} s"
        row = row_from_result(it, out, time.time() - t0, error)
        (out / "pool_row.json").write_text(json.dumps(row, indent=1))
        rows = [r for r in rows if r["slug"] != it["slug"]] + [row]
        rows.sort(key=lambda r: r["slug"])
        write_index(pool, rows)
        elapsed = time.time() - t_all
        eta = elapsed / i * (len(todo) - i)
        status = ("FAILED " + error) if error else \
            f"ok {row.get('tonic_label')} pcs={row.get('pcs')} notes={row.get('n_notes')}"
        print(f"[{i}/{len(todo)}] {it['slug']}: {status} "
              f"({row['runtime_s']:.0f} s; elapsed {elapsed / 60:.0f} min, eta {eta / 60:.0f} min)", flush=True)
    (pool / "POOL_DONE").write_text(time.strftime("%Y-%m-%d %H:%M:%S\n"))
    print("POOL_DONE", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
